### ISSUE TITLE
Add Valetudo map

### ISSUE THREAD

**Issue by rossiluis22** [denysdovhan/vacuum-card#102]
**Describe the solution you'd like**
i'm using Valetudo and I'd like to add the map instead the of vacuum image the map generated by 'custom:valetudo-map-card' so the card will show this map, this map is generated by a sensor 
the sensor:
sensor:
  - platform: mqtt
    state_topic: "valetudo/rockrobo/state"
    json_attributes_topic: "valetudo/rockrobo/map_data"
    name: xiaomi_map
    value_template: 'OK'

**Comment by krystiancharubin** [comment]
Card has basic support for maps using a camera entity. We don't have access to a vacuum that supports maps which makes further development on that front hard.

**Comment by krystiancharubin** [comment]
#33 describes how to get valetudo map working
