### ISSUE TITLE
Card does is not selectable in Lovelace

### ISSUE THREAD

**Issue by dkalinai** [denysdovhan/vacuum-card#103]
Cant seem to use this card in my installation.

Installed it with HACS, verified that it was installed and loaded under Lovelace resources. But when trying to add it in Lovelace, tells me cant find the card, also card itself is not selectable in lovelace UI.

**Comment by dkalinai** [comment]
<img width="593" alt="Screenshot 2020-08-23 at 21 53 30" src="https://user-images.githubusercontent.com/12793954/90986578-ae428a80-e58c-11ea-9f77-d0b53ff510f0.png">
<img width="990" alt="Screenshot 2020-08-23 at 22 00 28" src="https://user-images.githubusercontent.com/12793954/90986579-b00c4e00-e58c-11ea-872a-a61d8c492a57.png">

**Comment by dkalinai** [comment]
I am on Home Assistant 0.114.3 and Hacs 1.5.2

**Comment by dkalinai** [comment]
![Screenshot 2020-08-23 at 22 37 51](https://user-images.githubusercontent.com/12793954/90987134-55292580-e591-11ea-81ed-dbc32d261e47.png)

**Comment by lsljunior** [comment]
did you manage to solve it? I have the same issue.
Also installed it through HACS

**Comment by dkalinai** [comment]
Nope, still very much an issue for me m8. :( Hope creator responds eventually...

**Comment by thoompje** [comment]
Same issue here....

**Comment by krystiancharubin** [comment]
I recommend using manual mode and starting with the same from description.
The visual model does not support all the features of the card anyways.

**Comment by dkalinai** [comment]
It's not about visual or manual, the card itself is not even found... Even if installed via HACKs or manually. tried both ways and same error for card not found.

**Comment by krystiancharubin** [comment]
Try deleting vacuum-card.js.gz from www\community\vacuum-card.
Also clear your cache. Check if there are any errors listed in your browser console.

**Comment by lsljunior** [comment]
Dont know what happend, but somehow I was able to add the card using home assistant app for Android.
Maybe was something with my browser cache

**Comment by dkalinai** [comment]
Somehow cache is to blame here, would be good to have this step included in the install instructions. Managed to get it working now too.

**Comment by dkalinai** [comment]
May have been a custom theme too, who knows

**Comment by krystiancharubin** [comment]
This is not an issue for most users, but we can probably add a troubleshooting section that mentions clearing the cache when the card is not being recognized.
