### ISSUE TITLE
No sensor data

### ISSUE THREAD

**Issue by sliwkacz** [denysdovhan/vacuum-card#104]
**Before submitting a bug**

[ x] I updated to the latest version available
[ x] I cleared the cache of my browser

**Describe the bug**
The card doesn't show my sensor data at all. I was playing with toggles in the card configuration but with no success. Could the negative value for one of the sensors be the cause?

**Screenshots**
![obraz](https://user-images.githubusercontent.com/3290262/91161431-08496a00-e6cb-11ea-99fb-13c72d9cea6f.png)
![obraz](https://user-images.githubusercontent.com/3290262/91161476-15feef80-e6cb-11ea-8857-7caa50c30bac.png)

**Versions:**

- Release: [e.g. 1.6.0]
- Browser: [firefox]
- HomeAssistant version: [0.114.3]

**Comment by krystiancharubin** [comment]
You can only configure sensors in YAML mode. They are defined under the stats: tag.
Take a look at the example in the description. If you have something else than a Roborock then you will need to replace the attribute names with those your vacuum provides.

**Comment by sliwkacz** [comment]
Cool! It works, thank you!
