### ISSUE TITLE
Returning to dock hides the action buttons

### ISSUE THREAD

**Issue by sepodele** [denysdovhan/vacuum-card#107]
When the vacuum is returning to the dock the card has buttons saying 'Pause' or 'Continue' but all the action buttons are hidden. If I want the vacuum to then do another room I have to wait for it to dock before I can see the action buttons. Please make the action buttons visible while vacuum is returning to dock.

**Comment by denysdovhan** [comment]
You can stop (not pause) the robot and then send it to another room.

**Comment by sepodele** [comment]
Thanks. I can live with that.
