### ISSUE TITLE
Missing values in card

### ISSUE THREAD

**Issue by daveonkels** [denysdovhan/vacuum-card#11]
The card is displaying but is missing all of the sensor values. I've included a screenshot below. Installed in www folder and don't see any errors in my console. 

Expecting the values to display in Filter, Side Brush, Main Brush, etc.

<img width="508" alt="Screen Shot 2020-05-06 at 8 27 17 PM" src="https://user-images.githubusercontent.com/533642/81251510-4b76b480-8fd8-11ea-8205-3da4a9365efe.png">

<img width="364" alt="Screen Shot 2020-05-06 at 8 30 17 PM" src="https://user-images.githubusercontent.com/533642/81251566-6ba67380-8fd8-11ea-8637-0d8c84fdbe2a.png">

- Release: 0.3.2
- Browser: Tested in Chrome, Opera, and Safari
- HomeAssistant version: 0.109.4

**Comment by denysdovhan** [comment]
Please, try again with the latest `v.0.3.3` version.

**Comment by daveonkels** [comment]
Fixed and thank you for producing this excellent card. I've been waiting for something like this.

**Comment by denysdovhan** [comment]
Thanks!

If you really like it, consider supporting me on [Patreon](https://patreon.com/denysdovhan) (regular) or [Buy Me a Coffee](https://buymeacoff.ee/denysdovhan) (single time) 🙏
