### ISSUE TITLE
Possibility to switch between map view and vacuum view

### ISSUE THREAD

**Issue by aalbul** [denysdovhan/vacuum-card#124]
Hello,
First of all, thank you for fixing map view performance issue! That was fast and works perfectly for me!
The only problem that I still have is: when I define "map" attribute on the card, I cannot see my fancy vacuum image anymore.
The question is: is it possible to make a switch between map and vacuum view and allow users to choose which view should be the default one?

**Comment by krystiancharubin** [comment]
I'm glad the map fix is working well for you.
How would you switch between views? Currently clicking on the card opens the more info dialog.
Do you you want something more automatic, like when vacuum is docked it shows image, but when moving it shows the map?

**Comment by aalbul** [comment]
@krystiancharubin 
I was thinking about an additional button that allows switching between map/vacuum view + automatically switching view to map once robot starts working and back to Vacuum view when it is docked.
What I like about this approach Is that i can infer the state of the robot by looking at the state of card. I don't have to sit and watch it (or click more info) to understand if it is running right now or not.

![Screenshot 2020-10-07 at 14 37 34](https://user-images.githubusercontent.com/4253154/95331831-d66f1a00-08aa-11eb-9da4-dd3d0d09602b.png)

**Comment by KairuByte** [comment]
I'd like to second this. I wouldn't mind either option, or both. An automatic change to the map when cleaning would be quite useful, but I also wouldn't mind a button that swaps it.

**Comment by noorbertt** [comment]
Automatic changing would be useful, when the vacuum is docking or going back to the dock the vacuum shows but when it's doing it's job the map..

**Comment by NewRaiden** [comment]
> I'm glad the map fix is working well for you.
> How would you switch between views? Currently clicking on the card opens the more info dialog.
> Do you you want something more automatic, like when vacuum is docked it shows image, but when moving it shows the map?

It would be awsome if this could be allowed!

I'd really want map showing only if it is cleaning

**Comment by denysdovhan** [comment]
Nice feature! I'll gladly accept a PR if anyone is ready to implement this!

**Comment by cibernox** [comment]
I also ended up here because I thought it would be nice to be able to configure when I want to see the map and when to see the vacuum image.

Typically I care about the map when the vacuum is cleaning, but when it's docked I think I'd prefer to see the robot's image, much like stats can be configured.

```
map:
  cleaning: camera.t8_live_map
  default: false
```

Of course a toggle button as suggested above is also cool.

**Comment by KairuByte** [comment]
For anyone still looking for this, a workaround is to use the state-switch card. It allows you to swap between two versions of this card on the fly, depending on the state of the vacuum.

**Comment by SmartM-ui** [comment]
I was opening the same request.
I agree, it would be useful!
