### ISSUE TITLE
Generic card + charger fork

### ISSUE THREAD

**Issue by tmjo** [denysdovhan/vacuum-card#128]
**Generic + entity attributes**
Hi, really loved your card! Would be great to have this as a generic card too in addition to vacuum and purifier (like full custom flex on states and command toolbox) - it could then be used for so many things!! Great work!

Would also be awesome to be able to get attributes from _different_ entities than the main one for the stats.

**Charger fork**
Anyways, main reason for opening this is a question: Ok if I fork your card and make my modifications to make this a custom charger card? I have it working more or less, but wanted to reach out to you before putting it publicly on github to not be rude. I'm not an UI pro, so I depend 80-90% on your code as a starting point. Credits will be given of course :)

**Comment by tmjo** [comment]
Hi @denysdovhan; mind if I make a fork of your card suited for EV chargers?

**Comment by denysdovhan** [comment]
Sure, go for it! I would love to use some kind of generic card.

**Comment by tmjo** [comment]
Thanks @denysdovhan! I'll let u know how and where it goes and make sure to give you good credit!

**Comment by tmjo** [comment]
In case you want to have a look: Here is a very early pre-release of my [charger card](https://github.com/tmjo/charger-card). As you see, they visual stuff is very much similar to your splendid cards, but I've changed quite bit in code to adapt to charger use. Probably I've added tons of bugs and stuff too, so let's see how this goes. Thanks for your cards!!
