### ISSUE TITLE
Different rows of actions

### ISSUE THREAD

**Issue by bboudewijns** [denysdovhan/vacuum-card#131]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I have a lot of rooms in my house, the action row gets a bit cluttered with so many rooms. Would it be possible to have an option that you can divide your actions on multiple rows?

**Describe alternatives you've considered**
N/A

**Additional context**
![IMG_5536](https://user-images.githubusercontent.com/53646683/95966684-7a614400-0e1c-11eb-8a62-7b105d8acead.jpeg)

**Comment by sheminasalam** [comment]
did you find any solution to add multiple rows for actions? I am facing the same issue

**Comment by denysdovhan** [comment]
I'd made this row scrollable. I'll be grateful for a PR.

**Comment by denysdovhan** [comment]
Resolved recently. The row will be wrapped.
