### ISSUE TITLE
camera_thumbnail deprecation warning

### ISSUE THREAD

**Issue by Enzokot** [denysdovhan/vacuum-card#132]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**
Everytime I view my lovelace dashboard containing this card I get this warning in core log:
The websocket command 'camera_thumbnail' has been deprecated

**Steps to reproduce**

1. Add option "map" in config of custom:vacuum-card
2. Go to lovelace dashboard containing this card
4. See error in core log of HA

**Expected behavior**
Without warnings in core logs

**Screenshots**
![image](https://user-images.githubusercontent.com/43236573/96157209-af53c080-0f1a-11eb-9428-4e8e96b7d85f.png)

**Versions:**

- Release: 1.12.0
- Browser: chrome
- HomeAssistant version: 0.116.3

**Comment by brhahlen** [comment]
I'm seeing the same thing, which pollutes the logs quite a bit.

**Comment by bruvv** [comment]
Yup same here

**Comment by robertwigley** [comment]
It looks like the same issue was fixed in the [custom surveillance card](https://github.com/custom-cards/surveillance-card). Issue logged [here](https://github.com/custom-cards/surveillance-card/issues/22) and code available [here](https://github.com/custom-cards/surveillance-card/commit/1524fcbf95ff7e228ba3bc4c08bbfa5c018b825a). Maybe this helps?

**Comment by denysdovhan** [comment]
I know about this issue but didn't find any solution yet. @robertwigley It's nice you've found how others fixed that. I'll be grateful if you can send a PR with a fix.

**Comment by robertwigley** [comment]
@denysdovhan Sorry, I'm not a developer, so don't know how to fix it. I was hoping the links might help.

**Comment by grinstantin** [comment]
Fixed in 1.19.1.
