### ISSUE TITLE
this.hass is undefined

### ISSUE THREAD

**Issue by sermayoral** [denysdovhan/vacuum-card#133]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

I often get this error:

Logger: frontend.js.latest.202010012
Source: components/system_log/__init__.py:193
First occurred: 1:31:17 (2 occurrences)
Last logged: 1:58:33
http://homeassistant.local:8123/hacsfiles/vacuum-card/vacuum-card.js:522:37638 TypeError: this.hass is undefined 

**Steps to reproduce**

Nothing. It appears without doing anything.

**Versions:**

- Release: v1.12.0
- Browser: Firefox  81.0.2 (64 bits)
- HomeAssistant version: 0.116.4

**Comment by anhnvme** [comment]
i have the same issue

**Comment by krystiancharubin** [comment]
Dupe #125

**Comment by sermayoral** [comment]
It's not the same as #125. In our case, vacuum cleanes is showed in the card. Everything seems to work, but the log throws this error.

**Comment by krystiancharubin** [comment]
I was tracing the error for that issue and it also was being caused by this.hass being undefined. Card works other than live map.
Are you saying you are getting this error without having live map configured?

**Comment by sermayoral** [comment]
@krystiancharubin I'm not using live map and I'm getting this error

**Comment by adrianofoschi** [comment]
The same errore here with HomeAssistant v0.116.2 (dockerized) and card v1.12.0.
I'm not using live map too.

**Comment by bremor** [comment]
I get this error every time I look at the cards
`2020-12-10 22:16:21 ERROR (MainThread) [frontend.js.latest.202011112] http://192.168.10.200:8123/hacsfiles/vacuum-card/vacuum-card.js:522:37655 Uncaught TypeError: Cannot read property 'states' of undefined`

**Comment by sermayoral** [comment]
I can confirm this problem still happens in v1.13.0 :-(

**Comment by bremor** [comment]
I’ve created PR #159 to address this problem

**Comment by sermayoral** [comment]
@bremor thanks!! :-)

**Comment by denysdovhan** [comment]
Fixed. Will be available in the nearest release.
