### ISSUE TITLE
Align icons

### ISSUE THREAD

**Issue by cbuxton5200** [denysdovhan/vacuum-card#136]
Would it be possible to update the code to utilize the same icon for the "Locate Vacuum" function as the built-in Xiaomi Miio integration?  In the Lovelace card, it is a dot with a target around it, in the integration it is a map pin icon.  In the integration the dot with a square target has a function of "clean spot" so it's just a bit confusing.
[
![robo](https://user-images.githubusercontent.com/59487049/96500429-79f9ec00-1214-11eb-801a-2ab73d7c0c11.PNG)
](url)

**Comment by denysdovhan** [comment]
This should be very easy to fix. I'll be grateful if you send a PR 🙏🏻
