### ISSUE TITLE
Cleaning area and time empty

### ISSUE THREAD

**Issue by remusgondecjr** [denysdovhan/vacuum-card#138]
I have the Xiaomi Mijia 1C vacuum and successfully integrated using Concentricc code (https://github.com/Concentricc/xiaomi_vacuum). However, when the vacuum starts the cleaning process, cleaning area and time are showing empty. Do you know what may be the issue? Thanks!

**Comment by krystiancharubin** [comment]
You need to check what attributes are available for your vacuum under developer tools in HA.
Then update the card configuration with the attributes that your vacuum provides.
The example in the README is geared toward Roborock vacuums.

**Comment by remusgondecjr** [comment]
I see the attributes under developer tools, cleaning time and cleaning area - however they show empty.

**Comment by krystiancharubin** [comment]
can you post your card config and the yaml from developer tools

**Comment by remusgondecjr** [comment]
Card config:
type: 'custom:vacuum-card'
entity: vacuum.wall_e
image: default
compact_view: false
stats:
  default:
    - attribute: filter_left_time
      unit: hours
      subtitle: Filter
    - attribute: side_brush_time_left
      unit: hours
      subtitle: Side brush
    - attribute: main_brush_time_left
      unit: hours
      subtitle: Main brush
  cleaning:
    - attribute: cleaning_area
      unit: m2
      subtitle: Cleaning area
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time

Values from developer tools:
fan_speed_list: Silent, Standard, Strong, Turbo
battery_level: 100
battery_icon: mdi:battery
fan_speed: Standard
status: idle
error: NoError
main_brush_time_left: 297
main_brush_life_level: 99
side_brush_time_left: 197
side_brush_life_level: 98
filter_life_level: 98
filter_left_time: 147
cleaning_area: 
cleaning_time: 
total_cleaning_count: 6
friendly_name: Wall-e
supported_features: 12924

**Comment by myxor** [comment]
Cleaning time and area is empty for me as well but developer entity shoes these attributes as follows:

```
s_time: 24
s_area: 22.93
```


full attribute list:

```
fan_speed_list:
  - Silent
  - Standard
  - Medium
  - Turbo
battery_level: 100
battery_icon: 'mdi:battery-charging-100'
fan_speed: Silent
run_state: 5
mode: 0
err_state: 2105
battary_life: 100
box_type: 1
mop_type: 0
s_time: 24
s_area: 22.93
suction_grade: 0
water_grade: 12
remember_map: 1
has_map: 0
is_mop: 0
has_newmap: 0
status: docked
friendly_name: Rob
supported_features: 13180
```

**Comment by myxor** [comment]
I for myself found out that the attributes for cleaned area and cleaning time can be set in the `stats` `cleaning` settings:

which can be found in the Readme: https://github.com/denysdovhan/vacuum-card/blob/baf392fda674030c8910389ca7551ce0d83f6602/README.md#using-the-card

This solves this issue for me.

**Comment by denysdovhan** [comment]
Closing this since it seems like this question was answered. Correct me if I'm wrong.
