### ISSUE TITLE
Custom element doesn't exist: vacuum-card in V1.12.0

### ISSUE THREAD

**Issue by evgeniikim** [denysdovhan/vacuum-card#139]
Custom element doesn't exist: vacuum-card.

  - title: Clean
    icon: mdi:robot-vacuum
    cards:
      - type: 'custom:vacuum-card'
        entity: vacuum.xiaomi_vacuum_cleaner
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
          cleaning:
            - attribute: cleaned_area
              unit: m2
              subtitle: Cleaning area
            - attribute: cleaning_time
              unit: minutes
              subtitle: Cleaning time
        actions:
          - name: Clean living room
            service: script.vacuum_corridor
            icon: 'mdi:sofa'
          - name: Clean bedroom
            service: script.clean_bedroom
            icon: 'mdi:bed-empty'
          - name: Clean kitchen
            service: script.vacuum_kitchen
            icon: 'mdi:silverware-fork-knife'

**Comment by evgeniikim** [comment]
After add to config file, work correctly:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module

**Comment by nodeover** [comment]
I think the manual of has to be update for this issue.

**Comment by lelelic** [comment]
For who want to add the resource from Lovelance UI, the url should be local/vacuum-card.js and not /local/vacuum-card.js
