### ISSUE TITLE
Error: The websocket command 'camera_thumbnail' has been deprecated

### ISSUE THREAD

**Issue by tamas-czirjak-epam** [denysdovhan/vacuum-card#140]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

The log shows errors:
 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated

**Steps to reproduce**

1. Edit lovelace dashboard
2. Add the vacuum-card
3. See error on every page update and also periodically

**Expected behavior**
The errors should not be appearing.

**Versions:**

- Release: v1.12.0
- Browser: Chrome 86.0.4240.111 64bit
- HomeAssistant version: 0.116.4

**Comment by krystiancharubin** [comment]
dupe #132
