### ISSUE TITLE
Implement a 'return to base' button

### ISSUE THREAD

**Issue by mat4444** [denysdovhan/vacuum-card#142]
It would be great to have a 'return to base' button by default next to the start and locate buttons.
I know it's possible to create a script and place a shortcut, but it will be placed next to the 'actions' that I use for specific room cleaning. I my opinion, it would just look better next to the buttons on the left side.
Thank for considering this request !

**Comment by gurbina93** [comment]
Doesn't make sense to have the button there if it doesn't do anything while it is docked. When the vacuum is running the relevant buttons will be shown.
![image](https://user-images.githubusercontent.com/10726203/102818809-566a4200-440d-11eb-9979-dc818b736e4a.png)

**Comment by denysdovhan** [comment]
This button is already shown when vacuum is paused, cleaning or idle.
