### ISSUE TITLE
Home Assistant Core 0.118.3 - Card doens't work

### ISSUE THREAD

**Issue by luckyzor** [denysdovhan/vacuum-card#148]
Hello error on lovelace:

Home Assistant Core 0.118.3

![image](https://user-images.githubusercontent.com/31155573/100004028-31ab8c00-2dc7-11eb-9712-e8254287c9de.png)

![image](https://user-images.githubusercontent.com/31155573/100004114-50118780-2dc7-11eb-9141-d82cf79cc0ce.png)

can anyone help me?

**Comment by TobiasKneidl** [comment]
You have to add the card manually to your ressources in configuration.yaml if you use Lovelace in yaml mode:

Add reference to vacuum-card.js in Lovelace. There's two way to do that:
Using UI: Configuration → Lovelace Dashboards → Resources → Click Plus button → Set Url as /local/vacuum-card.js → Set Resource type as JavaScript Module.
Using YAML: Add following code to lovelace section.
resources:
  - url: /local/vacuum-card.js
    type: module
