### ISSUE TITLE
Round numerical data down to nearest number

### ISSUE THREAD

**Issue by ghost** [denysdovhan/vacuum-card#150]
**Is your feature request related to a problem? Please describe.**
I know you don't use valetudo, but unfortunately it exports usage data as a float, which i think is pretty useless and clutters the view

**Describe the solution you'd like**
It would be great if this is rounded down to the nearest number like in the original xiaomi data

**Describe alternatives you've considered**
The only real way would be to make custom sensors and pass it on there, and that would work. I'm aware this is a solution, but i think the fractions are meaningless anyway. It is unfortunately impossible to set it on valetudo side

<img width="404" alt="Screenshot 2020-11-25 at 23 00 48" src="https://user-images.githubusercontent.com/18247748/100285932-1466f100-2f72-11eb-9e34-092461957ebe.png">

**Comment by denysdovhan** [comment]
Should be pretty simple to do. I'll gladly merge a PR for that.

**Comment by jes1417** [comment]
will this PR also fix the battery %

![image](https://user-images.githubusercontent.com/38092747/118221509-5a8e0f00-b443-11eb-86cb-9d67a22ba2c5.png)
