### ISSUE TITLE
The vacuum status won't be updated until HA is restarted

### ISSUE THREAD

**Issue by likellindil** [denysdovhan/vacuum-card#152]
**Before submitting a bug**

[ ] I updated to the latest version available
[ ] I cleared the cache of my browser

**Describe the bug**

**Steps to reproduce**

1. Just use the vacuum and wait
2. The status will stop being updated after a period of time。
    For example, yesterday my vacuum worked after I left work, from 3 pm to 6 pm. 
    When I got home, it has been back to the charger, however, in HA, the status of the vacuum is 
    ![image](https://user-images.githubusercontent.com/62890839/100490905-6ec2a600-315a-11eb-8b96-6374b7ede8ab.png)
    It didn't change until I restarted the HA.

**Expected behavior**
The status should be updated in real0time.

**Screenshots**

**Versions:**

- Release: 1.12.0
- Browser: Edge
- HomeAssistant version: 0.118.4

**Comment by likellindil** [comment]
Forgot to mention that my vacuum is irobot i7

**Comment by hexfield** [comment]
Having the same issue here

**Comment by denysdovhan** [comment]
Sounds like an issue with HA, not the card. Please make sure the state of the vacuum is updated in HA.
