### ISSUE TITLE
websocket command 'camera_thumbnail' has been deprecated

### ISSUE THREAD

**Issue by mjkl-gh** [denysdovhan/vacuum-card#153]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**
Opening a tab with this card on it floods the logs with the following warning:

2020-12-03 20:52:57 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated
2020-12-03 20:52:59 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated

**Steps to reproduce**

1. Add card to tab
2. refresh the tab
4. See warnings in the logs

**Expected behavior**
This card probably uses websocket command 'camera_thumbnail'  which has been deprecated, resulting in a warning

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: 1.12.0
- Browser: chrome
- HomeAssistant version:0.118.4

**Comment by krystiancharubin** [comment]
Dupe #132

**Comment by mjkl-gh** [comment]
Aah excuse me didn't notice
