### ISSUE TITLE
Not displaying status/state

### ISSUE THREAD

**Issue by K-RAD** [denysdovhan/vacuum-card#154]
Card is not displaying the state of the robot entity. You can see below the entity state is Docked. And it doesn't change during cleaning either. (Status is enabled in the card)

![image](https://user-images.githubusercontent.com/3822874/101240895-77832100-36f2-11eb-96c6-67a8b2d51939.png)

Running a Deebot T8+ set up with [https://github.com/And3rsL/Deebot-for-hassio](https://github.com/And3rsL/Deebot-for-hassio)

**Comment by denysdovhan** [comment]
You sure you don't have `show_status` set to `false`?

**Comment by K-RAD** [comment]
I'm sure

`type: 'custom:vacuum-card'
entity: vacuum.ozzy
image: default
stats:
  default:
    - entity_id: sensor.ozzy_brush
      unit: '%'
      subtitle: Brush
    - entity_id: sensor.ozzy_sidebrush
      unit: '%'
      subtitle: Side Brush
    - entity_id: sensor.ozzy_heap
      unit: '%'
      subtitle: Filter
  cleaning:
    - entity_id: sensor.ozzy_stats_area
      unit: m2
      subtitle: Cleaning area
    - entity_id: sensor.ozzy_stats_time
      unit: minutes
      subtitle: Cleaning time
show_toolbar: true
show_status: true
show_name: true
`

**Comment by colino17** [comment]
I have the same issue. No status is displayed at any time.

**Comment by K-RAD** [comment]
@denysdovhan ?
