### ISSUE TITLE
Timer toggle

### ISSUE THREAD

**Issue by kimme1024** [denysdovhan/vacuum-card#155]
**Is your feature request related to a problem? Please describe.**
Not really a problem but my vacuum runs at night. However some nights we don't want the vacuum to work. For example when laundry is drying in the living room which  makes the vacuum gets stuk there or hits it.

**Describe the solution you'd like**
As I'm not using the pre-made actions provided in the example yaml I was hoping to be able to add a toggle that enables/disables the timer so I don't have to dive into the menu's of the companion app.

**Describe alternatives you've considered**
I tried making different scripts but I can't seem to find out what I have to do to be able to trigger the timer option:

```
timers:
  - enabled: true
```

Any help would be appreciated!

**Comment by denysdovhan** [comment]
This card does not implement any communications with the vacuum. It doesn't schedule anything, it doesn't communicate with the vacuum itself.

This card just displays the HA entity of the vacuum. It's just a convenient view of the vacuum.

You should probably report your issue to the HA repo.
