### ISSUE TITLE
Ability to change which service the start button calls

### ISSUE THREAD

**Issue by clarsonJWU** [denysdovhan/vacuum-card#158]
Would like the ability to change what service is called when you hit the start button (or any of the default buttons). The card works perfect with my Deebot N79, except for the start button. This button is coded to call the vacuum.start service, which my vacuum doesn't respond to. When I call the service vacuum.turn_on it works. If there was an ability to map these default buttons to a service of our choosing, that would make the card much more flexible.

I confirmed this by deleting the gz file, and editing the js and changing this.callService("start") to this.callService("turn_on")

**Comment by jeremysherriff** [comment]
This is also a possible way to resolve #165

**Comment by floodwayprintco** [comment]
I have a problem this would solve as well, sometimes my vacuum gets lost starting a full clean, but is super reliable when I send it to my own sequence of rooms. Would be great to have the same customization as the other side of the panel.

**Comment by denysdovhan** [comment]
This must be pretty easy to solve. I'll be grateful if any of you send a PR with this feature.

**Comment by denysdovhan** [comment]
Already released.
