### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by andriej** [denysdovhan/vacuum-card#16]
**Is your feature request related to a problem? Please describe.**
It would be nice if card could benefit from translated strings regarding brushes etc.

**Additional context**
If not possible to get value automatically, would be nice to let users help translate.

**Comment by denysdovhan** [comment]
Nice feature! I will consider that!

**Comment by cschriel** [comment]
I am willing to translate this to dutch if required.

**Comment by stormnetgd** [comment]
If necessary, I will gladly translate it into Polish.

**Comment by deluxestyle** [comment]
I can help to translate this to german. Would really love it

**Comment by denysdovhan** [comment]
Working on it!
I'll translate this to Ukrainian (as my native language).

**Comment by denysdovhan** [comment]
Released as `1.0.0` along with #29.

Waiting for your PRs with translations.

**Comment by stormnetgd** [comment]
Translated to Polish:

stats:
  default:
    - attribute: filter_left
      unit: godz.
      subtitle: Filtr
    - attribute: side_brush_left
      unit: godz.
      subtitle: Zmiotka
    - attribute: main_brush_left
      unit: hours
      subtitle: Szczotka
    - attribute: sensor_dirty_left
      unit: godz.
      subtitle: Sensor
  cleaning:
    - attribute: cleaned_area
      unit: m2
      subtitle: Obszar
    - attribute: cleaning_time
      unit: min
      subtitle: Czas trwania
docked - W stacji
cleaning - Sprząta
returning - Wraca
Dock - Stacja
Pause - Pauza
Stop - Stop
Continue - Kontyntynuj
