### ISSUE TITLE
camera_thumbnail deprecated error 

### ISSUE THREAD

**Issue by Rrapa** [denysdovhan/vacuum-card#160]
**Before submitting a bug**

[X ] I updated to the latest version available
[X ] I cleared the cache of my browser

**Describe the bug**
WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated

I'm flooded with that warning above. When I removed add in it stops. Can you please have a look? 

**Versions:**

- Release: [1.13]
- Browser: [any]
- HomeAssistant version: [2020.12.7 - but same issue on previous version as well]

**Comment by gmkrib** [comment]
Same here, this appears when you will use the live map.

**Comment by DendelX** [comment]
same here... isn't this card maintained?

**Comment by denysdovhan** [comment]
This is a deprecation warning inside the HA. AFAIK HA dev docs do not provide any alternative yet.

We have to live with it someone finds an alternative solution.

**Comment by denysdovhan** [comment]
Duplicate of #132
