### ISSUE TITLE
Cannot read property 'states'

### ISSUE THREAD

**Issue by ingeniumdesign** [denysdovhan/vacuum-card#169]
Hi all,

i have all the time a **Error:**
`hacsfiles/vacuum-card/vacuum-card.js:522:37655 Uncaught TypeError: Cannot read property 'states' of undefined`

**Versions:**

- Release: v1.13.0
- HomeAssistant version: 2020.12.2
- Roborock S6

Thanks!

**Comment by chatlamin** [comment]
I have the same error.
Versions:

- Release: v1.13.0
- HomeAssistant version: 2021.1.1
- Xiaomi vacuum cleaner 1s

**Comment by denysdovhan** [comment]
Should be fixed by #133. Please reopen if the issue persists after updating to the next version.
