### ISSUE TITLE
Repeats for room segment cleaning

### ISSUE THREAD

**Issue by noorbertt** [denysdovhan/vacuum-card#171]
HI,

There is a way to add repeats for my script?
I have a few smaller area and I would like to clean those more than 1 time.

alias: vacuum_hallway
sequence:
  - service: vacuum.send_command
    data:
      command: app_segment_clean
      params:
        - 19
    entity_id: vacuum.xiaomi_vacuum_cleaner
mode: single

**Comment by denysdovhan** [comment]
You can pass [`service_data`](https://github.com/denysdovhan/vacuum-card#actions-object), this should work if I understand your problem correctly. Anyway, it might depend on your setup and environment.
