### ISSUE TITLE
Deenkee 700 support

### ISSUE THREAD

**Issue by a8ree** [denysdovhan/vacuum-card#176]
I'd like to use this with my Deenkee 700

I've determined that the start button does not work

I've tried to use custom actions but cannot get it to work

This is how I make a call to start the robot

https://www.dropbox.com/s/7z7d4kl5c1delfd/Screenshot%202021-01-25%20at%2022.04.44.png?dl=0

Hoping someone might be able to advise how to align this to work correctly

Thanks!

**Comment by denysdovhan** [comment]
This looks like a problem with a vacuum setup, not a card. Try asking on [Home Assistant forum](https://community.home-assistant.io/).
