### ISSUE TITLE
Allow URL to be launched in actions

### ISSUE THREAD

**Issue by baloo-gh** [denysdovhan/vacuum-card#179]
Love your card, great work! One thing I would wish for: 

To have in the status bar the option to not only call a service like today ("clean room X"), but to allow putting a clickable icon in there which will launch a new browser window with a pre-defined target. In essence mimicking what the famous "button card" offers:

  - type: button
    tap_action:
      action: url
      url_path: IP-ADDRESS TO OPEN

I would love to have that feature, as it would allow me to quickly tap on the status bar to go into the Valetudo webapp and fiddle with the map there for example.

Maybe doable in one of the next rounds of upgrades? Thanks a ton already now for considering!

**Comment by denysdovhan** [comment]
Nice idea! I'll gladly accept a PR with such functionality.

**Comment by baloo-gh** [comment]
Thank you! Unfortunately I am miserable in coding - good enough to apply the wonderful stuff you and others develop for Home Assistant, but not good enough to find the code to inject into. I did try though before saying that! This is not an urgency, whenever you would see this as a potential thing to add, just think of the idea, ok? For now, I am having a very "bloody" workaround by putting a button card under yours; has the functionality I desire, just looks a bit crap :-)

**Comment by denysdovhan** [comment]
Sure, I'll add you to my backlog.

**Comment by baloo-gh** [comment]
Thank you!!!

**Comment by baloo-gh** [comment]
I cannot really code, though at least I can create nice workarounds :-)  Here is how I was able to construct this nearly perfectly. In essence, using a "Grid Card" (1 column only) with two cards in there:    1) A custom button card leveraging your color scheme   and blending in seamlessly with your card (so it looks like 1 card only)    2) Your lovely card.

Looks:
![image](https://user-images.githubusercontent.com/45927782/106687510-8724c600-65cc-11eb-8c1f-9bb59a0e8685.png)

YAML code for the custom button card:
type: 'custom:button-card'
name: Zur Webapp
aspect_ratio: 20/1
color_type: card
color: 'rgb(0, 170, 245)'
tap_action:
  action: url
  url_path: 'http:/XXX.XXX.XXX'
styles:
  card:
    - font-weight: bold
    - font-size: 15px

Hope that helps anyone who might look for something similar, until this may become part of the status bar in the future :-)
