### ISSUE TITLE
Show the name

### ISSUE THREAD

**Issue by julianrinaldi** [denysdovhan/vacuum-card#18]
This is a great plugin, but it doesn't display the name of the vacuum. I have four RoboRock S6 (you can add this model to the list btw, it works great) and I have no idea which card is for which vacuum unless I click on them. Being able to see the name of the vacuum is pretty essential for anyone with more than one vacuum.

**Comment by denysdovhan** [comment]
Good point! Let's think about it.

**Comment by denysdovhan** [comment]
Published as `0.5.0`!
