### ISSUE TITLE
Remove Blue

### ISSUE THREAD

**Issue by mrigau** [denysdovhan/vacuum-card#181]
Great card
Please add the option to remove the blue background of the card

**Describe alternatives you've considered**
Loading an image still leave areas in blue

**Comment by pasiz** [comment]
Could you take a screenshot, i cannot understand what you mean with the blue background? I have green theme and map loaded, but no blue in there

**Comment by mrigau** [comment]
I'm using the Shark IQ
Also are the hours entries supported for this model?

![image](https://user-images.githubusercontent.com/78067218/107164197-55bd4900-6984-11eb-94be-791898877d28.png)

**Comment by denysdovhan** [comment]
Duplicate of #5
