### ISSUE TITLE
Adding Amarey A900 vacuum

### ISSUE THREAD

**Issue by DragonDub** [denysdovhan/vacuum-card#187]
Hello, I got a Amarey A900 vacuum cleaner and I would like to use it in hass. I read the DPs for the vacuum in different states but couldn't figure everything out (3 out of 9 DPs are missing).

**Comment by denysdovhan** [comment]
This is not a question for us. We do not provide any integration for vacuums, we just provide the UI for controlling already integrated vacuums. You should ask for help on [HA Community Forum](https://community.home-assistant.io/).
