### ISSUE TITLE
HA Logs report: Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../"

### ISSUE THREAD

**Issue by paulearley** [denysdovhan/vacuum-card#193]
The HA error log reports: Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../"

"lit-element" is from this component's javascript. My setting in lovelace is: 
image: /local/community/vacuum-card/Roomba960.png

I cleared the cache and reloaded the component from HACS. I checked to be sure the component was properly placed in \www\community\vacuum-card.

**Versions:**

Version: core-2021.3.3
Installation Type: Home Assistant Supervised
Browsers: chrome, brave

**Comment by denysdovhan** [comment]
Seems like you've downloaded a source file instead of a compiled one. Please, use one of the [provided installation methods](https://github.com/denysdovhan/vacuum-card#installing). HACS is preferable.

**Comment by paulearley** [comment]
Thanks. That seemed to have fixed it. 


This was sent from my iPhone.
Please excuse the brevity, typos or informality of my message.
