### ISSUE TITLE
Hide Play / locate

### ISSUE THREAD

**Issue by jensorium** [denysdovhan/vacuum-card#194]
Hey,

thx a lot for your work! Works really well. Had to connect valetudo and Xiaomi, as it wasnt showing the m2 from valetudo and the time in minutes, but now it looks great. ( stacked 2 vacuum cards) Only 2 things:

In Xiaomi i cant change the Fan speed, it shows 60 all the time even if i change it in Valetudo.
So can i just hide the top row? Or should i make sensor from the attributes of xiaomi to show in the valetudo card? 

didn't find a solution, but as  I am using gen 1 i got Problems with start cleaning. is it possible to hide the play button?

Kind Regards

Jens

**Comment by denysdovhan** [comment]
I don't think this is possible at the moment. You're welcome to introduce that feature.
