### ISSUE TITLE
only english language, pls help

### ISSUE THREAD

**Issue by czarnydlk** [denysdovhan/vacuum-card#195]
Hi, How can i change lang? The entity setings are in polish but status are in english "Docked"? Do i need to upload somewhere pl.json from src folder?

**Comment by denysdovhan** [comment]
The language is set automatically, based on HA language.

**Comment by czarnydlk** [comment]
So it's dosent. I have language set Polish and still see in English. Change language to another and back to Polish didnt help

**Comment by xguitoux** [comment]
Hello, same here, not a big problem for me but the card remains in english but my HA is in french
