### ISSUE TITLE
Add @macbury as a contributor

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/vacuum-card#2]
Hi @macbury 👋

This project is heavily inspired by your custom card for the vacuum cleaner. I refactored it a bit and added some minor features.

I believe this might be useful for you as well. I also invited you to contribute to this project (please, check your email).

**Comment by macbury** [comment]
![noice](https://media.giphy.com/media/PhKhSXofSAm3e/giphy.gif)

**Comment by denysdovhan** [comment]
@macbury can you check it with map option? I don’t want to flash my robot, so I can’t test this. 

I will be grateful for a screenshot or gif, so I can put it in Readme.
