### ISSUE TITLE
Camera_thumbnail warning

### ISSUE THREAD

**Issue by sagitt** [denysdovhan/vacuum-card#202]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

After last HA update, this card generate a warning

see here https://github.com/home-assistant/core/issues/49105

**Steps to reproduce**

**Expected behavior**

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [e.g. 0.2.0]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [e.g 0.109.4]

**Comment by grinstantin** [comment]
Fixed in 1.19.1.
