### ISSUE TITLE
Support rest980 roomba

### ISSUE THREAD

**Issue by ajtudela** [denysdovhan/vacuum-card#22]
Hi, Is it possible to make the card compatible with [ha-rest980-roomba](https://github.com/jeremywillans/ha-rest980-roomba)? 
I think is the best and most complete integratation of iRobot Roombas for Home Assistant. 

And your card i sso awesome!

**Comment by denysdovhan** [comment]
If this integration implements a [template vacuum API](https://www.home-assistant.io/integrations/vacuum.template/), then it should be supported.

**Comment by ajtudela** [comment]
I maked my own template vacuum but the card shows empty
