### ISSUE TITLE
(Re)Define the robot image grey/plain rendering based on chosen robot state

### ISSUE THREAD

**Issue by r-jean-pierre** [denysdovhan/vacuum-card#235]
Currently, I understand the robot image is "greyed" in some specific cases such as "charging" or "docked". But at least, the Neato D3 never enters into the "idle" mode, and its icon transparency never switches to plain

It took me (a long!) time to understand that the D3 has a strange way of charging (please see the attached image on battery history):
it never reaches 100% of the battery, but it cycles between 98 and 99%, it's a continuous alternates of little charges and discharges. It is somehow always in the charging mode, the "idle" just does not exist.

Anyhow I would like to ask : how can the end user define that the state "docked" will have the non-greyed icon as the state "idle"?

Hope the image will help you to understand my long text :-)

![2021-06-24 20_08_38-YAML Dashboard - Home Assistant](https://user-images.githubusercontent.com/9727894/123311989-0d17be00-d528-11eb-9cf8-9860dc38ad65.png)

**Comment by paulius2k** [comment]
@r-jean-pierre - please share your Neato Botvac's svg picture file? :)
