### ISSUE TITLE
Add attributes for iRobot Braava M6

### ISSUE THREAD

**Issue by natdm** [denysdovhan/vacuum-card#236]
**Is your feature request related to a problem? Please describe.**
While the card works with mops, there are attributes that are used that could be changed (`fan_speed`), and attributes that could be used that are not (`tank_level`, `detected_pad`). Also the image could be changed. 

Here's an example of the mop entity:
```json
{
   "status":"Charging",
   "fan_speed":"Standard-3",
   "fan_speed_list":[
      "Standard-1",
      "Standard-2",
      "Standard-3",
      "Deep-1",
      "Deep-2",
      "Deep-3",
      "Extended-1",
      "Extended-2",
      "Extended-3"
   ],
   "battery_level":99,
   "battery_icon":"mdi:battery-charging-100",
   "friendly_name":"Thelma Mop",
   "tank_level":0,
   "detected_pad":"reusableDry"
}
```

**Describe the solution you'd like**
- The `fan_speed` is actually the cleaning depth. That could be changed to some form of `Wet Mopping Behavior` (which is what it's called in the app), described in detail below.
- The `tank_level` could be shown somewhere
- the `detected_pad` which has 
  - `reusableWet`
  - `reusableDry`
  - `invalid`
  - Wet (official name needed)
  - Dry (official name needed)

About the `fan_speed` list, which was for sure hijacked for the braava m6: it can be utilized to find more than one attribute. The template is `{cleaning style}-{jet spray amount}`. Eg: 
- `Extended-3` means the mop is doing an extended clean, and it's doing high amounts of jet spray.
- `Standard-2` is doing the standard clean, and a normal amount of jet spray.

**Describe alternatives you've considered**
I've attempted to do it myself (and will continue to do so), and I've got something almost working, but it's not really my forte. I will continue to work on it but this is probably like an hour of someones time if they're efficient in html/css design, along with the libraries used here for styling. I'm more than willing to collaborate and test it locally.

**Additional context**

**Comment by denysdovhan** [comment]
There are lots of vacuums with different integrations and properties. It's hard to support all of them consistently. Let's hear a feedback from more users.

**Comment by tiduspup** [comment]
Hello

also having some brave m6 and was looking how to solve this issue 

so if anybody works on it please let me know
