### ISSUE TITLE
not sending commands

### ISSUE THREAD

**Issue by MiniSkyDiver** [denysdovhan/vacuum-card#240]
Hi!
After update homeassistant to 2021.7.1 lowlace card lost function of control vacuum. But still shows it status.

If i rolling back to 2021.6.6 - all start working.
What i should do to fix it?

**Versions:**

- Release: [e.g. 0.2.0]
- Browser: [firefox and application Homeassistant]
- HomeAssistant version: [2021.7.1]

**Comment by kdelios** [comment]
Same happened to me. Remove your vaccum.yaml and restart HA. Millo integration is from UI
