### ISSUE TITLE
Reduce map update rate (or disable) when idle

### ISSUE THREAD

**Issue by RoboMagus** [denysdovhan/vacuum-card#243]
**Is your feature request related to a problem? Please describe.**
It seems the 'camera' image of the map keeps updating once every 5 seconds, even when the robo vac is docked and just chilling. Especially when on a metered connection on a phone this is a waste.

**Describe the solution you'd like**
Ability to disable or reduce the rate of updating the map image when the vacuum is idle / docked. Maybe even provide the option to fall back to a static image when idle instead.

**Comment by denysdovhan** [comment]
Good idea. PR is welcome.
