### ISSUE TITLE
Use Templates for stats or actions

### ISSUE THREAD

**Issue by lanrat** [denysdovhan/vacuum-card#248]
**Is your feature request related to a problem? Please describe.**

I use a helper date to keep track of the last time my vacuum ran, and I display the value in the `stats` section of this card.
However it displays the value in its raw form. It would be nice if templates could be used to format it like the rest of the UI,

**Describe the solution you'd like**

It would be nice to use templates for the `stats` and `actions` portion of the config.

**Describe alternatives you've considered**
Using a separate card to just display this metadata

**Additional context**

<img width="514" alt="Screen Shot 2021-08-02 at 2 40 39 PM" src="https://user-images.githubusercontent.com/164192/127927306-22809a03-6519-4830-9515-3062f54fe419.png">

**Comment by Szesi111** [comment]
Hi,

The same problem for "mijia.vacuum.v2"
Cleaned area reported without dot separator. 1234 means 12.34
I use Xiaomi Miot integration.

thx

**Comment by denysdovhan** [comment]
This would be a nice feature. Feel free to open a PR for that, because I don't have time to work on that feature.
