### ISSUE TITLE
Ability to remove sensors

### ISSUE THREAD

**Issue by julianrinaldi** [denysdovhan/vacuum-card#25]
First, you can add the iRobot Braava Jet M6 to the list of supported devices. It works, but there is obviously no reason to have the filter or brush sensors for a robot mop, so it would be nice to be able to hide them.

**Comment by cschriel** [comment]
My Roomba 960 does not support the sensors. I would like to delete them aswell.
![image](https://user-images.githubusercontent.com/14190796/81506981-5001dc80-92fa-11ea-9bf1-b3a434c98392.png)

**Comment by denysdovhan** [comment]
Should be resolved by #29. It will be released as 1.0.0.
