### ISSUE TITLE
Text displayed on the card with fully charged battery

### ISSUE THREAD

**Issue by mretegan** [denysdovhan/vacuum-card#26]
**Is your feature request related to a problem? Please describe.**
Change the text displayed on the card once the battery is 100%.

**Describe the solution you'd like**
Instead of "Charging" it would display "Charged"

**Comment by denysdovhan** [comment]
I use built-in states. In most cases, the robot doesn't report such a state as `charged`. I can check if the battery is 100%, though. Let's consider that.

**Comment by denysdovhan** [comment]
It believes it's better to stick with built-in statuses rather than inviting our own. Sorry, but this issue won't be resolved anytime soon.
