### ISSUE TITLE
how can I enter the water level next to the fan, if available

### ISSUE THREAD

**Issue by RW-7** [denysdovhan/vacuum-card#260]
how can I enter the water level next to the fan, if available on Deebot
![deboot](https://user-images.githubusercontent.com/65983282/131654960-9e5ff15b-db04-4596-9a44-9ae6b9753c7c.JPG)

**Comment by denysdovhan** [comment]
I don't have a Deebot to test or implement this. Please, send a PR if you know how to do that.
