### ISSUE TITLE
mijia.vacuum.v2

### ISSUE THREAD

**Issue by larsoss** [denysdovhan/vacuum-card#261]
I recently bought from the mijia.vacuum.v2. This is partly supported, and therefore I have added the following data here. Would be a nice addition.

fan_speed_list:
  - Silence
  - Stanrd
  - Middle
  - Enchance
battery_level: 76
battery_icon: mdi:battery-80
fan_speed: Stanrd
model: mijia.vacuum.v2
lan_ip: 
mac_address: 
firmware_version: 2.0.8
hardware_version: ''
entity_class: MiotVacuumEntity
miot_type: urn:miot-spec-v2:device:vacuum:0000A006:mijia-v2:2
vacuum.status: 2
vacuum.fault: 0
vacuum.mode: 1
vacuum.target_water_level: 2
vacuum.fan_level: 1
other_status.mop_status: 1
language: 0
language.not_disturb_switch: false
language.not_disturb_time.error: '-704040003 Property does not exist'
language.time_zone.error: '-704040003 Property does not exist'
clean_record.clean_area: 2220
clean_record.clean_time: 29
clean_record.total_clean_area: 55786
clean_record.total_clean_time: 657
clean_record.total_clean_count: 24
remote_control.direction_key.error: '-704030013 Property is not readable'
map.map_switch.error: '-704040003 Property does not exist'
brush_life_level-15-1: 91
brush_left_time-15-2: 8205
brush_cleaner.brush_life_level: 96
brush_cleaner.brush_left_time: 17285
filter.filter_life_level: 92
filter.filter_left_time: 8285
alarm: true
alarm.volume: 50
battery.battery_level: 76
battery.charging_state: 0
state_updater: cloud
sub_entities:
  - filter-11.filter_life_level-1
  - filter-11.filter_left_time-2
  - battery-3.battery_level-1
  - battery-3.charging_state-2
  - brush_cleaner-14.brush_life_level-1
  - brush_cleaner-14.brush_left_time-2
  - brush_cleaner-15.brush_life_level-1
  - brush_cleaner-15.brush_left_time-2
friendly_name: Dweilrobot
supported_features: 12536

**Comment by denysdovhan** [comment]
Thanks, but I don't know what to do with this info
