### ISSUE TITLE
Vacuum Speeds strings

### ISSUE THREAD

**Issue by tarasifua** [denysdovhan/vacuum-card#263]
**Is your feature request related to a problem? Please describe.**
Hello! Can you please add fan speeds "low" and "max" into your card, as on screenshot?

<img width="440" alt="Знімок екрана 2021-09-20 о 22 05 51" src="https://user-images.githubusercontent.com/1798483/134060180-3d147e73-77c1-4b78-ab20-021f02ced6de.png">

Taking this opportunity, I also want to ask, is there any chance to ask you to add water usage control into your card? 
Thank you in advance!

**Comment by denysdovhan** [comment]
There's a PR for #304
