### ISSUE TITLE
ha-icon-button no longer supports icon="" in 2021.11

### ISSUE THREAD

**Issue by mortenmoulder** [denysdovhan/vacuum-card#276]
After updating to 2021.11 I noticed that all icons were missing from this integration.

I created an issue on the Home Assistant Frontend repository, only to find that `ha-icon-button` has changed behavior. This is not listed in the official update's "breaking changes" section, because using `ha-icon-button` is technically wrong, since it's a Home Assistant component/element, that should not be used by developers. Read more on my issue here: https://github.com/home-assistant/frontend/issues/10521

**Comment by craigueh** [comment]
I also have this issue. Is there a workaround?

**Comment by mortenmoulder** [comment]
@craigueh Not until @denysdovhan or another person (via pull request) fixes it. For now, you can revert back to 2021.10 if it bothers you too much.

**Comment by bstrakt** [comment]
until it's fixed, you can manually edit vacuum-card.js and modify the following lines:

line 394:
replace:
></ha-icon-button>`;
with:
><ha-icon icon="${icon}"></ha-icon></ha-icon-button>`;

line 402:
replace:
>
with:
><ha-icon icon="hass:home-map-marker"></ha-icon>

line 412:
replace:
>
with:
><ha-icon icon="hass:play"></ha-icon>

line 419:
replace:
>
with:
><ha-icon icon="mdi:map-marker"></ha-icon>

You must maintain the spacing (just replace the code from the line with the new code without deleting the space before it).
Clear browser or app cache and it should work.
