### ISSUE TITLE
There is no translation into Russian

### ISSUE THREAD

**Issue by stylishkrio** [denysdovhan/vacuum-card#280]
There is no translation into Russian. Release: v2.1.0 
![There is no translation](https://user-images.githubusercontent.com/77132140/140607930-3090f2bc-be43-42da-9ecd-dad8e4024a95.PNG)

**Comment by denysdovhan** [comment]
It's not a bug, there's just no such key in the `ru.json`: https://github.com/denysdovhan/vacuum-card/blob/master/src/translations/ru.json#L12-L18

Please, open a PR, if you want a fix for that.
