### ISSUE TITLE
Actions icons missing from Toolbar

### ISSUE THREAD

**Issue by craigueh** [denysdovhan/vacuum-card#282]
On latest release v2.2.0 and Homeassistant 2021.11.1 the Actions icons are missing from the bottom toolbar. They don't even render with missing icons. On the left the Clean and Locate icons are there but on the right where the Actions icons should be the whole div is just empty.

**Comment by craigueh** [comment]
My bad, i read over the latest install guide and see that the "actions:" section was renamed to "shortcuts:". Once I updated my config the shortcuts now work as expected. Hope this helps someone..

**Comment by ralong777** [comment]
> My bad, i read over the latest install guide and see that the "actions:" section was renamed to "shortcuts:". Once I updated my config the shortcuts now work as expected. Hope this helps someone..

How can I do this?

**Comment by denysdovhan** [comment]
2.0.0 introduced a breaking change. There's a warning in the console for that.
