### ISSUE TITLE
Documentation regarding Shark IQ - How to call specific room cleaning?

### ISSUE THREAD

**Issue by bobloadmire** [denysdovhan/vacuum-card#286]
**Before submitting a bug**

[X ] I updated to the latest version available
[X ] I cleared the cache of my browser

The card works fine with my vacuum. There is an example config to clean specific rooms and how a cleaning map. The shark IQ supports both of these functions in the app, but there is no documentation on how to call these specific services for this robot. Where would I find this information? The official page for the Shark IQ integration on the HA website doesn't even list all of the modes automatically supported by HA natively, such as suction mode, charge amount, etc.

**Comment by denysdovhan** [comment]
I can't help you with that. Try asking in the Shark IQ integration repo.
