### ISSUE TITLE
[suggestion] Only show map while cleaning

### ISSUE THREAD

**Issue by Stooovie** [denysdovhan/vacuum-card#288]
Right now, it's always show or always hide.

Proposal: provide a way to only show the vacuum map while cleaning

Thanks!

**Comment by ImagineerNL** [comment]
+1
This cleans up my view a lot.
I like the docked and animated picture too, so i currently have 3 panels where i think it should/could fit in one.

1- the vacuum card with (animated) picture with all functions and stats
2- the vacuum card with livemap without any functions
3- an image card showing the downloaded picture of the Last Clean Image

**Comment by denysdovhan** [comment]
Worth considering.
