### ISSUE TITLE
Unable to see icon and shortcuts. 

### ISSUE THREAD

**Issue by limlaw** [denysdovhan/vacuum-card#290]
Greeting this card is awesome, i just manage to integrate my Dreame 2C P2140 with Dreame D9 (https://github.com/pooyashahidi/xiaomi_vacuum) most of the command and state works. I am using this card most features works as well. I have a small issue with the icon it is not appearing in the toolbar. It just show blanks. But i hover i can see the tag and click it is working. Wonder if any clue how i can I resolve this? Or is it becuase my intergration of Dreame 2c P2140 does not works well?

it jsut show no icon tools bar.
![image](https://user-images.githubusercontent.com/9285460/141603332-75770731-efc6-4b65-8000-299a69de38f8.png)

Hover i can see the tag name.
![image](https://user-images.githubusercontent.com/9285460/141603382-ad373c35-c7a2-4e9d-90d0-3b0ae5be3c35.png)

I can see when it returning to docking station.
![image](https://user-images.githubusercontent.com/9285460/141603361-90189e26-833d-4afd-94f9-fba092e76deb.png)

Any help would be appreciated. I managed to try run locally vacuum-card.js but couldn't figure out how to solve this. I was trying to add the set_water_level but got hard time getting it right. Keep complaning service doesn't exist. set_water_level doesn't exist

**Comment by chreggy** [comment]
Hello limlaw,

I have the same problem like you. I'm using the Slate theme if it can help to debug.


![HA_Roborock_Bug](https://user-images.githubusercontent.com/17594324/141678411-9b03b109-65ba-49be-99db-9f6e1d37036e.PNG)

**Comment by raptr55** [comment]
Same here with home assistant version 2021.11.03 and a roborock s5max vacuum

**Comment by raptr55** [comment]
Solution found in other issue: replace action: with shortcuts:

**Comment by chreggy** [comment]
> 
> 
> Solution found in other issue: replace action: with shortcuts:

I have tested this solution without success in the morning

![HA_Roborock_Bug](https://user-images.githubusercontent.com/17594324/141684524-291e42a8-d3a2-4f4a-92d6-491ef12aa544.PNG)

**Comment by rruizGit** [comment]
Same exact issue with HASSIO 2021.11.3 and Vacuum Card v2.2.2 with a Neato D7.

**Comment by limlaw** [comment]
i ended up editing the vacuum-card.js using the source code [how to run locally](https://github.com/denysdovhan/vacuum-card/blob/master/CONTRIBUTING.md#how-to-run-locally) researching and tweaking a bit i guess this part for example most of the icons in js were like that e.g moving the html close tag to end in ha-icon >

        const buttons = shortcuts.map(
          ({ name, service, icon, service_data }) => {
            const execute = () => {
              this.callAction({ service, service_data });
            };
            return html`<ha-icon-button title="${name}" @click="${execute}"
              **>**<ha-icon icon="${icon}"></ha-icon
            **>**</ha-icon-button>`;
          }
        );

i moved this part so i would tag in html see bold.

        const buttons = shortcuts.map(
          ({ name, service, icon, service_data }) => {
            const execute = () => {
              this.callAction({ service, service_data });
            };
            return html`<ha-icon-button title="${name}" @click="${execute}"
              <ha-icon icon="${icon}"></ha-icon>**>**
			  </ha-icon-button>`;
          }
        );

inaddtional when i was doing cleaning mine seems to have animation, as result checking that mine was state in moipping rather than cleaning. 

original is:

    switch (state) {
      case 'on':
      case 'auto':
      case 'spot':
      case 'edge':
      case 'single_room':
      case 'cleaning': {

added 

    switch (state) {
      case 'on':
      case 'auto':
      case 'spot':
      case 'edge':
      case 'single_room':
      case 'cleaning':
      **case 'sweeping**':
      **case 'mopping**': {


in style.js

  .vacuum.on,
  .**vacuum.cleaning**,
  .**vacuum.sweeping**,
  .vacuum.auto,
  .vacuum.spot,
  .vacuum.edge,
  .vacuum.mopping,
  .vacuum.single_room {
    animation: cleaning 5s linear infinite;
  }

  .vacuum.returning {
    animation: returning 2s linear infinite;
  }

  .vacuum.paused {
    opacity: 100%;
  }

  .vacuum.docked {
    opacity: 50%;
  }

  .fill-gap {
    flex-grow: 1;
  }

for water function i added this in vacuumcard-js

after 

  callService(service, isRequest = true, options = {}) {
    this.hass.callService('vacuum', service, {
      entity_id: this.config.entity,
      ...options,
    });

    if (isRequest) {
      this.requestInProgress = true;
      this.requestUpdate();
    }
  }

added

  **callServiceXiaomi(service, isRequest = true, options = {}) {
    this.hass.callService('xiaomi_vacuum', service, {
      entity_id: this.config.entity,
      ...options,
    });**

**at** 

  handleSpeed(e) {
    const fan_speed = e.target.getAttribute('value');
    this.callService('set_fan_speed', false, { fan_speed });
  }

added

  **handleWater(e) {
    const water_level = e.target.getAttribute('value');
    this.callServiceXiaomi('vacuum_set_water_level', false, { water_level });
  }**

added somewhere in 

  getAttributes(entity) {
    const {
      status,
      state,
      fan_speed,
      fan_speed_list,
      **water_level,
      water_level_list,**
      battery_level,
      battery_icon,
      friendly_name,
    } = entity.attributes;

    return {
      status: status || state || entity.state,
      fan_speed,
      fan_speed_list,
      **water_level,
      water_level_list,**
      battery_level,
      battery_icon,
      friendly_name,
    };
  }

after renderSource() {...}

  **renderWater() {
    const { water_level: source, water_level_list: sources } = this.getAttributes(
      this.entity
    );

    if (!sources) {
      return html``;
    }

    const selected = sources.indexOf(source);

    return html`
      <paper-menu-button
        slot="dropdown-trigger"
        .horizontalAlign=${'right'}
        .verticalAlign=${'top'}
        .verticalOffset=${40}
        .noAnimations=${true}
        @click="${(e) => e.stopPropagation()}"
      >
        <paper-button slot="dropdown-trigger">
          <ha-icon icon="mdi:water"></ha-icon>
          <span show=${true}>
            ${localize(`source.${source}`) || source}
          </span>
        </paper-button>
        <paper-listbox
          slot="dropdown-content"
          selected=${selected}
          @click="${(e) => this.handleWater(e)}"
        >
          ${sources.map(
            (item) =>
              html`<paper-item value=${item}
                >${localize(`source.${item}`) || item}</paper-item
              >`
          )}
        </paper-listbox>
      </paper-menu-button>
    `;
  }**

![image](https://user-images.githubusercontent.com/9285460/141727249-8c92d50a-6531-4356-858e-7ff4dd731dd5.png)

I am using model: Mijia Robot Vacuum-Map 2C my state always in mopping regardless
model code: dreame.vacuum.p2140
