### ISSUE TITLE
Translation improvement for Dreame 1C o other mop+vacuum cleaners

### ISSUE THREAD

**Issue by ghiki** [denysdovhan/vacuum-card#291]
I added an attribute to show the water level configured in mop cleaning (in my case for Mijia 1C)

    - attribute: water_level
      subtitle: Nivel de agua

But I've looked the JS and this isn't translated:
The available options are "High, Med, Low" 
![imagen](https://user-images.githubusercontent.com/854302/141693278-7fdee782-fbc7-4316-b771-7cc363e2e19d.png)

Is it possible to add these to translations (in Spanish these levels are "Alto, Medio, Bajo")?

**Comment by ghiki** [comment]
Maybe also create an action in the card  for "set_water_level" service
![imagen](https://user-images.githubusercontent.com/854302/141694067-be32d06a-15c0-4ff9-b686-6878c5b17a4e.png)

**Comment by ghiki** [comment]
@denysdovhan possible to do something?

**Comment by denysdovhan** [comment]
Water levels are in the progress. See #304
