### ISSUE TITLE
Cant install it manually

### ISSUE THREAD

**Issue by wurliwax** [denysdovhan/vacuum-card#297]
[x] working on latest versions

Hi!

I do not have HACs and I hesitate to install it. 
Nevertheless the vacuum card is awesome and I want to use it. I strongly followed the instructions for manually installation and the log says:

"
2021-11-20 11:47:17 ERROR (MainThread) [frontend.js.latest.202111090] http://192.168.178.75:8123/config/lovelace/resources:0:0 Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".
"

Seems to be similar problems as described here at the beginning: https://github.com/denysdovhan/vacuum-card/issues/76
I managed to get other custom cards installed manually the same way. (e.g. https://github.com/kalkih/mini-graph-card)
I am using a raspi and installed the pre-configured packege from HA.
I also used the latest release from https://github.com/denysdovhan/vacuum-card/releases/tag/v2.2.2 - and copied only the .js file into the www folder of my config.

Any hints what could help to install it without HACS?

BR
Michael

**Comment by denysdovhan** [comment]
Do not download the repo — the repo contains uncompiled code.

Try downloading a file attached to the releases, here's the latest one: https://github.com/denysdovhan/vacuum-card/releases/tag/v2.5.1

You can find `vacuum-card.js` file attached to every release. Use that file.

Read manual installation instruction carefully: https://github.com/denysdovhan/vacuum-card#manual
