### ISSUE TITLE
Status unknown

### ISSUE THREAD

**Issue by sephrioth** [denysdovhan/vacuum-card#298]
The status of vacuum card shows "unknown", but I checked the attributes, it should be "Charging Completed"

fan_speed_list: Silent, Basic, Strong, Full Speed 
battery_level: 100 
battery_icon: mdi:battery 
fan_speed: Basic 
model: dreame.vacuum.p2149o 
firmware_version: 4.1.8_1065 
hardware_version: Linux 
vacuum_status: Charging Completed 
vacuum_fault: 68 
vacuum_mode: 1 
vacuum_room_ids: null 
battery_battery_level: 100 
battery_charging_state: Charging 
filter_filter_life_level: 95 
filter_filter_left_time: 143 
friendly_name: Xiaomi Vacuum Cleaner 
supported_features: 8312

**Comment by denysdovhan** [comment]
This is the problem with HA integration, not this card. Doublecheck you configuration.
