### ISSUE TITLE
Card not compatible with Xiaomi Miio integration

### ISSUE THREAD

**Issue by andreaconfa** [denysdovhan/vacuum-card#303]
Hi all,
i have this card running for an year and all worked like a charme.
Now i started over with my home assistant and i found that adding the roborock ( i have an S5 and a S6 Pure) via the integration page expose all the attributes as a separate sensors and this is not compatible with the card.

![image](https://user-images.githubusercontent.com/44619437/143932158-fd703f71-8570-41b3-a25d-812bf067e79c.png)
![image](https://user-images.githubusercontent.com/44619437/143932214-12bc075d-77f1-4d0e-a513-49aca3429cfb.png)

**Comment by Henry-Sir** [comment]
https://github.com/denysdovhan/vacuum-card/issues/279

**Comment by denysdovhan** [comment]
It is compatible. I have my vacuum setup via `xiaomi_miio`. You can set up stats via template sensors.
