### ISSUE TITLE
Unable to add custom actions

### ISSUE THREAD

**Issue by danielzrob** [denysdovhan/vacuum-card#307]
**Before submitting a bug**

[ Y] I updated to the latest version available
[ Y] I cleared the cache of my browser

**Describe the bug**

Unable to add actions to the tool bar. 

**Steps to reproduce**

Code in my card: 

type: custom:vacuum-card
entity: vacuum.wall_e_2
image: default
show_toolbar: true
show_status: true
show_name: true
compact_view: false
actions:
  - name: Update
    service: script.vacuum_update_state
    icon: mdi:update

**Expected behavior**
I should get a little button in the bottom right of the tool bar. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24725085/145472369-05c4d688-24ff-4369-8910-ce648c408c45.png)

**Versions:**

- Release: [2.2.5]
- Browser: [Chrome, Android App]
- HomeAssistant version: [2021.11.5]

It is a very real possibility that I am just doing something wrong. If so, sorry!

**Comment by weitheng** [comment]
Some of the previous functions of `actions` have been replaced by `shortcuts` read [here](https://github.com/denysdovhan/vacuum-card#actions-object), you now have to change `actions` to `shortcuts` to achieve the functions you want. However, there seems to be a bug where even if you use shortcuts, nothing shows up.

**Comment by danielzrob** [comment]
Yeah I can see stop and dock, but not the custom ones. 

Ok I will keep an out for an update and just use some buttons for my scripts. 

Thanks for the fast reply!

**Comment by airampg** [comment]
Make sure the icon you are using is good because they changed the way icons work too!

**Comment by stezak77** [comment]
My shortcuts are visible only when the vacuum is docked.
I was expecting my shortcuts to be always accessible.
Is it as expected? I can't find this documented.

**Comment by danielzrob** [comment]
Got it working ! Thanks! Here is my card:

type: custom:vacuum-card
entity: vacuum.wall_e_2
image: default
show_toolbar: true
show_status: true
show_name: true
compact_view: false
shortcuts:
  - name: Clean living room
    service: script.wall_e_clean_living_room
    icon: mdi:sofa
    service_data:
      rooms:
        - Living Room
  - name: Night Cleaning
    service: script.wall_e_night_cleaning
    icon: mdi:robot-vacuum
view_layout:
  position: sidebar

**Comment by Hukuma1** [comment]
Switching code from `actions` to `shortcuts` worked for me too. Thank you!

```
actions:
  - name: Clean living room
```

```
shortcuts:
  - name: Clean living room
```
