### ISSUE TITLE
Support for Deebot 600 series

### ISSUE THREAD

**Issue by bartandeweg** [denysdovhan/vacuum-card#31]
Great card!

The cards works with my Deebot 600 series. But no information on the sensors. The Deebot is pretty straight forward. And have the following items: 

fan_speed_list:
  - normal
  - high
status: auto
battery_level: 89
battery_icon: 'mdi:battery-90'
fan_speed: normal
error: null
component_main_brush: 26513
component_side_brush: 11513
component_filter: 8513
clean_mode: auto
friendly_name: Moppie
supported_features: 10239

Can this one be supported as well?

**Comment by krystiancharubin** [comment]
This card was originally built for Roborock/Xiaomi which names stat attributes as `<name>_left`. This is why none of the stats data is shown for your Deebot. #29 allows to fully configure the stats area, so you will be able to specify which attributes you want show depending on the state of the vacuum.

**Comment by denysdovhan** [comment]
Should be resolved by #29. It will be released as 1.0.0.
