### ISSUE TITLE
Sensor unknow rockrobo.vacuum.v1

### ISSUE THREAD

**Issue by anhnvme** [denysdovhan/vacuum-card#310]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

Due Home Asssistant Xiaomi Miio Intergated migrate attribute to sensor entity, it's not showing anymore.
Can you help me migrate it ?
**Screenshots**
![](https://i.imgur.com/NqH8oOS.png"")
![](https://i.imgur.com/T3AzhfJ.png"")
![](https://i.imgur.com/u9XuT9q.png"")
**Versions:**

- Release: [2.2.5]
- Browser: [Safari]
- HomeAssistant version: [2021.11.4]

**Comment by Sygnus83** [comment]
Hi !
I have the same problem, whit my gen 1 robot vacuum.

![image](https://user-images.githubusercontent.com/92396929/147851340-e9749ad4-cf49-41e6-99f1-53682447e93e.png)

**Comment by anhnvme** [comment]
fixed by chang from `attribute` to `entity_id`
