### ISSUE TITLE
After last HA update(.. 11.5) the card for vacuum cleaner doesn't show digits (cleaning time, m2, e. t. c) 

### ISSUE THREAD

**Issue by alexandr-sova** [denysdovhan/vacuum-card#312]
**Before submitting a bug**

[ ] I updated to the latest version available
[ ] I cleared the cache of my browser

**Describe the bug**

**Steps to reproduce**

3. See error

**Expected behavior**

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [e.g. 0.2.0]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [e.g 0.109.4]

![Screenshot_20211210_202850_io homeassistant companion android](https://user-images.githubusercontent.com/37264392/145624359-53b6ac36-aec9-4bb3-9582-a770228be30f.jpg)

**Comment by Dutchstyler** [comment]
Having the same issue.
OS: 6.0 on RPI4
core-2021.11.5
supervisor-2021.12.1

Xiaomi Roborock S50

Nice too see i`m not the only one.

**Comment by airampg** [comment]
Agreed I have this issue too. However, adding the separate sensor entities will not get this fixed as they are in different units than the attributes used to be. Currently, the workaround is to use templates to turn the sensors back into sensible units and add those to the card instead. Hopefully, the card can be updated to handle the sensor entities on its own and turn them into sensible units.

**Comment by JayZiii** [comment]
Yes got the same problem.. i deleted "attribute" with "entity" and it works. But next problem: the unit of measurement now are seconds and not hours. Is there a possibility to change it to hours ?

**Comment by ferropolis** [comment]
Hey, same as @JayZiii
I have change from

> stats:
  default:
    - attribute: filter_left
      unit: hours
      subtitle: Filter
    - attribute: side_brush_left
      unit: hours
      subtitle: Side brush
    - attribute: main_brush_left
      unit: hours
      subtitle: Main brush
    - attribute: sensor_dirty_left
      unit: hours
      subtitle: Sensors
  cleaning:
    - attribute: cleaned_area
      unit: m2
      subtitle: Cleaning area
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time

**Comment by ferropolis** [comment]
Quick workaround: 

I have add the following code into configuration.yaml
```
template:
  - sensor:
      - name: "converted_helene_wischer_total_duration"
        unit_of_measurement: "h"
        state: >
            {% set total_duration = states('sensor.helene_wischer_total_duration') | float %}
            {{ (total_duration / 3600) | round(1, default=0) }}
      - name: "converted_helene_wischer_filter_left"
        unit_of_measurement: "h"
        state: >
            {% set total_duration = states('sensor.helene_wischer_filter_left') | float %}
            {{ (total_duration / 3600) | round(1, default=0) }}
```

**Comment by cvocvo** [comment]
Thanks @ferropolis that works well!
Another artifact from this change seems to be (at least for me) that these two attributes no longer exist?
```
cleaning:
    - attribute: cleaned_area
      unit: m2
      subtitle: Cleaning area
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time
```
I see however we have sensors `sensor.roborock_last_clean_duration` and `sensor.roborock_last_clean_area`, but when the vacuum is cleaning these values are from the previous run and not the current run.

Anyone have a fix for that?

**Comment by ferropolis** [comment]
@cvocvo 
test or look at ```sensor.helene_wischer_total_clean_area``` and ```sensor.helene_wischer_total_duration```

**Comment by fdegraeve** [comment]
I have the same issue as @cvocvo, do you find a fix ?

**Comment by dapuzz** [comment]
Quick and dirty solution to get hours back:
`<span class="stats-value">${Math.round( n / 3600 )}</span>`
...

**Comment by JayZiii** [comment]
> Quick and dirty solution to get hours back: `<span class="stats-value">${Math.round( n / 3600 )}</span>` ...

Where do i have to add this ?

**Comment by h1nnak** [comment]
> > Quick and dirty solution to get hours back: `<span class="stats-value">${Math.round( n / 3600 )}</span>` ...
> 
> Where do i have to add this ?

In vacuum-card.js

**Comment by verstrepeng** [comment]
Can't this be merged in the code ?

**Comment by helderjrvieira** [comment]
Hi, I just changed the stats-value span, but the card is with the same issue.
I already restarted it. Some suggestion? Instead of using a template?
Thanks

**Comment by jpleite** [comment]
> Quick and dirty solution to get hours back:
> `<span class="stats-value">${Math.round( n / 3600 )}</span>`
> ...

Tried that by replacing previous `<span class="stats-value">${n}</span>`. However I see no changes in frontend. Any help pls?

**Comment by ToXinE** [comment]
> I have the same issue as @cvocvo, do you find a fix ?
I had to manually enable those sensors (XXXX_last_clean_area, XXXX_last_clean_start, XXXX_last_clean_ended etc.) that were disabled by the integration.

**Comment by denysdovhan** [comment]
Try using the newly added `value_template` feature in stats.
