### ISSUE TITLE
Bot animation when mopping

### ISSUE THREAD

**Issue by Twan-V** [denysdovhan/vacuum-card#315]
When "cleaning", the vacuum image in the lovelace card is animated to represent a cleaning action.
When "mopping", no animation is shown. Can the cleaning animation be added here as well?

The image already has a class 'mopping':
`<img class="vacuum mopping" src="/local/lovelace/my-vacuum.png">`

Probably, when adding the mopping class to styles.js is sufficient to make this work:
https://github.com/denysdovhan/vacuum-card/blob/master/src/styles.js#L119

```
  .vacuum.on,
  .vacuum.cleaning,
  .vacuum.auto,
  .vacuum.spot,
  .vacuum.edge,
  .vacuum.single_room,
  .vacuum.mopping {
    animation: cleaning 5s linear infinite;
  }
```

**Comment by denysdovhan** [comment]
Yes, just send a PR for that. My vacuum doesn't have mopping functionality, so I didn't add it in the first place.
