### ISSUE TITLE
Q: Is there a way to show a "locate" button in the toolbar when the vacuum is active/paused/stuck?

### ISSUE THREAD

**Issue by jeremysherriff** [denysdovhan/vacuum-card#316]
**Is your feature request related to a problem? Please describe.**
Is there a way to show the `locate` button when the vacuum is operational, especially when it is cleaning and/or paused (stuck)?  I see the custom `shortcut` toolbar buttons are only visible when the vacuum is docked or stopped, and the `actions` options appear to only change the service call behind the buttons.

**Describe the solution you'd like**
I would find it useful to use the `locate` function when the vacuum is "cleaning" and gets stuck ("paused" state) - often this is under a bed or behind furniture. 

**Describe alternatives you've considered**
I could add a normal Lovelace button or entity card and use vertical-stack to make it near to the Vacuum card, but with the custom `shortcut` buttons already implemented it would be nice to keep everything in one card.

Another alternative is to open the native Xiaomi app and use the locate function.  I would prefer to use HA/Lovelace interface.

**Comment by denysdovhan** [comment]
This sounds useful. I'll consider this in the future. Thanks!
