### ISSUE TITLE
Options to remove hours data

### ISSUE THREAD

**Issue by likellindil** [denysdovhan/vacuum-card#32]
Thanks for the great card!
It works with my iRobot S7+ very well.
The only issue I met with is that there is no data shown for those filters, brush, or sensor.
Is this normal?
If this can't be fixed easily, is there any option to just hide that section and leave the rest parts (battery status, vacuum image, and command icons) available?

Thank you!

**Comment by krystiancharubin** [comment]
This card was original made for Roborock/Xiaomi vacuums. #29 will allow you to configure the stats using any attributes your vacuum exposes. Leaving stats configuration empty will hide it from the card.

**Comment by denysdovhan** [comment]
Should be resolved by #29. It will be released as 1.0.0.
