### ISSUE TITLE
Can't add images, ?

### ISSUE THREAD

**Issue by robb99** [denysdovhan/vacuum-card#320]
I assume, maybe falsely, that you add the path of the 
image you want displayed in the text box on the card.  But that does not seem to work, I just get a broken image icon.  Are there special requirements for the image?

**Comment by mcoops** [comment]
Did you upload the image to your Home Assistants www dir? i.e. `/config/www/`?

HA then maps that path as `/local`. So in the vacuum card itself reference the image as:

```yaml
image: /local/roomba.png
```

**Comment by spr0k3t** [comment]
I've had to go in to the www/community/vacuum-card/ directory and delete the gzip file, then clear the browser cache before.

**Comment by denysdovhan** [comment]
This is described in HA docs. You are free to send a PR with such explanation.
