### ISSUE TITLE
Entity values math manipulations

### ISSUE THREAD

**Issue by YSmetana** [denysdovhan/vacuum-card#322]
Hello! Thank you for your work!

As a user, I would like to use `entity_id` in the `stats` section of the card config 
but convert entity value, 
so, for example, value in seconds can be divided to 3600 to show hours instead of seconds.

Starting from HASS 2021.11.0, I believe, Xiaomi Vacuum integration reports some data not as attributes, but as sensors. E. q.:

- main brush left;
- side brush left;
- filter left;
- sensor dirty left.

Furthermore, the values are now in seconds. 

![image](https://user-images.githubusercontent.com/2463895/148541009-334c9930-227b-400d-a0dd-bf1126ae5bbd.png)

The seconds are not useful to visualize, so I would better show it as hours. But for this, I need to do some math with the value.

Maybe templating, so - entity_id_value_template: `{{ states.sensor.roborock_filter_left.state | int / 3600 }} `would be possible,
or some `convert_unit `option etc.

Thank you!

**Comment by YSmetana** [comment]
I have got some hints from the related thread:

> please report to the card developer that they should use the native_measurement_unit and convert the data for display as they see fit.

https://github.com/home-assistant/core/issues/59027#issuecomment-1008334428

**Comment by whattheschnell** [comment]
I also noticed the same issue. Would be nice to avoid templating separately

**Comment by gcorgnet** [comment]
Works on my machine :-)
![image](https://user-images.githubusercontent.com/4731735/160177556-4bb6f39d-7d40-4cee-84f7-0e90d9076d12.png)
