### ISSUE TITLE
Custom element doesent exist: vacuum-card.

### ISSUE THREAD

**Issue by hanseandersson** [denysdovhan/vacuum-card#326]
Card is not available in home assistant app.
i have removed and reinstalled the vacuum card, and its working in chrome, both on computer and mobile, but in home assistant mobile app, the card does not exist.
![Screenshot_20220123-132523](https://user-images.githubusercontent.com/60035776/150679438-79c7d188-8273-4518-856a-a425065eeee0.png)
![Screenshot_20220123-132516](https://user-images.githubusercontent.com/60035776/150679442-c0bfcae6-6a1a-42c5-9e62-92c2ff562bb0.png)

**Comment by oscarb** [comment]
Have you tried force quitting the app and then open it again? That has helped me in the same situation.

**Comment by krystiancharubin** [comment]
clear cache of the app

**Comment by denysdovhan** [comment]
This is happening due to cache problems, most likely. Try fully reloading the UI, app, etc.
