### ISSUE TITLE
Background color is incorrect when using themes

### ISSUE THREAD

**Issue by vmartinv** [denysdovhan/vacuum-card#337]
**Describe the bug**

I'm using the theme ios-dark-mode-red-alternative, the icons at the bottom are barely legible because it is not using the correct background. 

**Steps to reproduce**

1. Install theme ios-dark-mode-red-alternative
2. Add vacuum card
3. See error

**Expected behavior**
The appropiate backgorund (a transparent black) present in the rest of my cards is missing (thermostat included as example).

**Screenshots**
<img width="471" alt="Screenshot 2022-02-24 at 10 00 38" src="https://user-images.githubusercontent.com/5374768/155502313-ab90d392-0555-4596-8974-ba15e34c5603.png">

<img width="477" alt="Screenshot 2022-02-24 at 09 53 10" src="https://user-images.githubusercontent.com/5374768/155501084-7f849d08-ef76-4485-94ab-11fafc549854.png">

**Versions:**

- Release: v2.3.0
- Browser: chrome
- HomeAssistant version: 2022.02.08

**Comment by vmartinv** [comment]
@stezak77 This is also incorrect, the background should respect the theme settings, not be transparent. This is what the buttons look with your fix.
<img width="472" alt="Screenshot 2022-03-18 at 01 24 47" src="https://user-images.githubusercontent.com/5374768/158919815-bef20557-f659-497e-aff8-7857397eccfc.png">

**Comment by stezak77** [comment]
@vmartinv Can you check my workaround using the default home assistant theme?
In my case, the toolbar inherits the card background so it looks ok.

**Comment by vmartinv** [comment]
> @vmartinv Can you check my workaround using the default home assistant theme? In my case, the toolbar inherits the card background so it looks ok: ![image](https://user-images.githubusercontent.com/49878007/159035309-5993f25f-c285-4099-9bcd-be62557703d0.png)

The fix should work with all themes not just the default one, it needs to have the same style as the rest of the widgets. Your workaround actually makes it look worse on my end so it definitely shouldn't be pushed.
