### ISSUE TITLE
Card not showing correctly on HA 2022.3

### ISSUE THREAD

**Issue by hmmbob** [denysdovhan/vacuum-card#338]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

Drop down is not shown correctly on HA 2022.3.0b1
![image](https://user-images.githubusercontent.com/33529490/155515066-fddf14ec-6965-436f-838a-ac36013f0d00.png)

No errors in console. Probably due to decommissioning of `paper-item` in HA frontend.

**Steps to reproduce**

3. See error

**Expected behavior**

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [e.g. 0.2.0] latest (2.2.7)
- Browser: [e.g. chrome, safari] Chrome
- HomeAssistant version: [e.g 0.109.4] 2022.3.0b1

**Comment by axcs** [comment]
I confirm have the same bug

**Comment by Kalembang** [comment]
Same issue:
![image](https://user-images.githubusercontent.com/71909170/156507362-bb09a78a-e1a8-415c-b606-73218069a200.png)

**Comment by tenkaibr** [comment]
Same problem here.

**Comment by ivanovd** [comment]
Same

**Comment by patagonaa** [comment]
Please stop spamming peoples' notifications and just use the thumbs up reaction on the original post if you have the same issue.
Judging by the readme, the dev most likely has more important things to do right now, so either try fixing the issue (if you can) or just wait for a fix.
[kalkih/mini-media-player](https://github.com/kalkih/mini-media-player) had a similar issue with 2022.3.0 so maybe that can be helpful when implementing a fix.

**Comment by luixal** [comment]
Same problem, it also happens with the minimal view.

**Comment by JackPala** [comment]
Same issue

**Comment by hmmbob** [comment]
It has been fixed. Upgrade the card through HACS and clear caches
