### ISSUE TITLE
Words of support

### ISSUE THREAD

**Issue by V4n1X** [denysdovhan/vacuum-card#339]
Hey man,
just want to write that I hope you're safe also in the future, end this war ends fast. 
We should all make love not war.
I have no words for what happend actually, but we should support UA the best we can.

You're release notes are a good way to make people listening to this!

Stay safe!

**Comment by n506** [comment]
There should be no politics on github

**Comment by akarpych** [comment]
Скоро станете свободными людьми! Здоровья семье и близким.

**Comment by Bl3rp** [comment]
> There should be no politics on github

There should also be no war in the world

**Comment by harddistortion** [comment]
Hey man, when your government, soldiers, nazists and mercenaries were killing Ukrainians (civilians, women, children and the elderlyin) in Donbass region for far-fetched reasons, you as well as other part of civil world were keeping silence, how did your government called them? Terrorists! Thousands of people who were forced to defend their home from their "compatriots" were killed without trial and investigation with tacit consent. 
Take the blinders off your eyes and start already thinking with your brains, and not with the shit that your media supply you with. Europe, the USA, Australia are calling for peace and at the same time pumping Ukraine with money and lethal weapons, for what? To make the peace talks more peaceful? Bullshit! 
EIGHT, god damn EIGHT damned years, people in Donbass were living in constant fear to be killed by UKRAINIANS!
You listened to horror stories for 4 days and started screaming at the top of your lungs that a Russian bear attacked you. But what about the voice of the civilians of Donbass (citizens of Ukraine), who for 8 years shouted for help, but received only heavy fire from mortars, rockets and small arms from the soldiers of the Armed Forces of Ukraine?! You are to blame for what happened, and there is no need to blame everything on Russia, it was you who staged a genocide to your own citizens, it was you who blocked the drinking water to the residents of Crimea, then have the courage to admit it, sofa warriors.

**Comment by elahd** [comment]
@n506 & @harddistortion: Seriously? You guys are antagonizing an individual civilian who is _currently homeless_ because of an invasion that has been denounced by the governments and citizens of just about every non-autocratic country _on the planet_. Posting this here in really bad taste, to say the least.

I was on the fence about donating to the Ukrainian military—that felt like more of a government-to-government affair—but you two inspired me to pull the trigger. I sent over ~$100 in BTC.

@denysdovhan: Good luck and stay safe!

**Comment by dimmuboy** [comment]
> Hey man, when your government, soldiers, nazists and mercenaries were killing Ukrainians (civilians, women, children and the elderlyin) in Donbass region for far-fetched reasons, you as well as other part of civil world were keeping silence, how did your government called them? Terrorists! Thousands of people who were forced to defend their home from their "compatriots" were killed without trial and investigation with tacit consent. Take the blinders off your eyes and start already thinking with your brains, and not with the shit that your media supply you with. Europe, the USA, Australia are calling for peace and at the same time pumping Ukraine with money and lethal weapons, for what? To make the peace talks more peaceful? Bullshit! EIGHT, god damn EIGHT damned years, people in Donbass were living in constant fear to be killed by UKRAINIANS! You listened to horror stories for 4 days and started screaming at the top of your lungs that a Russian bear attacked you. But what about the voice of the civilians of Donbass (citizens of Ukraine), who for 8 years shouted for help, but received only heavy fire from mortars, rockets and small arms from the soldiers of the Armed Forces of Ukraine?! You are to blame for what happened, and there is no need to blame everything on Russia, it was you who staged a genocide to your own citizens, it was you who blocked the drinking water to the residents of Crimea, then have the courage to admit it, sofa warriors.

Are you from UA or why this crazy message?

**Comment by denysdovhan** [comment]
> Скоро станете свободными людьми! Здоровья семье и близким.

Русский коментатор на Гитхабе, иди нахуй.

**Comment by denysdovhan** [comment]
@elahd @V4n1X @dimmuboy @Bl3rp thanks for your support! I am grateful to the bottom of my heart ❤️

P.S: Don't be bothered with Russian supporters. I will not tolerate them after everything that happened. They are going to fix bugs on their own - they go straight to the ban list.

**Comment by baggein** [comment]
Stop politics, please!

**Comment by denysdovhan** [comment]
@baggein my life depends on this so-called politics. I don't care if you like it or not. I don't like sitting in the basement and hearing sirens as well.

You're free to use another project if you don't like the banner.

**Comment by khmm12** [comment]
@denysdovhan please don't pay attention to people who support the war. I won't be surprised if some of this people are Lakhta trolls. Russians, who haven't lost their mind, are with you. 

Be safe and take care 🙏

**Comment by oschmidteu** [comment]
Thanks for your work. I just found your card and donated to Ukraine’s Armed Forces.
Slava Ukraini!

**Comment by denysdovhan** [comment]
Thanks for telling me words of support! I just released a new version of the card: fixed rounded corners and migrated code to TypeScript (which should lead to more stable code).

Closing this…

P.S: If you find this card useful for you, [consider sending me a tip](https://www.buymeacoffee.com/denysdovhan). Thanks!
