### ISSUE TITLE
Unable to upgrade from 2.3.1 to 2.3.2

### ISSUE THREAD

**Issue by JackPala** [denysdovhan/vacuum-card#343]
**Before submitting a bug**

[ ] I updated to the latest version available
[ X] I cleared the cache of my browser

**Describe the bug**
I am having the issue on 2.3.1 where the dropdown menu is always visible for fan speed. I see that 2.3.2 fixes this however when I try to update to 2.3.2 I have the option to reload my browser, upon clicking this my page reloads but my instance remains on 2.3.1

This also persists across all of my devices both before and after clearing the browser cache. Rebooting the home assistant instance also seems to keep it on 2.3.1

**Comment by krystiancharubin** [comment]
Try uninstalling and reinstalling.

**Comment by JackPala** [comment]
Upon uninstalling, the www directory empties itself out, but the card remains on my lovelace interface and I am now unable to re-install

**Comment by krystiancharubin** [comment]
Sounds like your HACS setup is broken, you can try manually installing using the steps in the README

**Comment by JackPala** [comment]
Indeed you were right, HACS is completely broken
