### ISSUE TITLE
Show zone map

### ISSUE THREAD

**Issue by Wyfy0107** [denysdovhan/vacuum-card#345]
**Is your feature request related to a problem? Please describe.**
Currently the card does not show a map nor an option to choose a zone to be vacuumed

**Describe the solution you'd like**
It would be great to be able to choose which area for vacuum from the card

**Describe alternatives you've considered**

**Additional context**
I'm using a dreame.mc1808 robot

**Comment by denysdovhan** [comment]
Hey! That would be a cool feature, but it's too difficult to implement. It requires a lot of code and logic, which I'm ready to deliver. 

Meanwhile, try using this card: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
