### ISSUE TITLE
Disable image

### ISSUE THREAD

**Issue by edgard** [denysdovhan/vacuum-card#35]
Is there a way to disable the image to make the card more compact?

Thanks, awesome work!

**Comment by denysdovhan** [comment]
Added `compact_view` option. Will be released soon.

**Comment by edgard** [comment]
You're awesome, thank you very much!

**Comment by denysdovhan** [comment]
@edgard if you like it, consider supporting on [Buy Me a Coffee](https://www.buymeacoffee.com/denysdovhan) or [Patreon](https://www.patreon.com/denysdovhan).
