### ISSUE TITLE
Drop down list (fan speeds) is not displayed completely

### ISSUE THREAD

**Issue by edenhaus** [denysdovhan/vacuum-card#365]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**
This bug was already fixed by #341 in version `v2.3.3` and reintroduced in `v2.4.x`
The original issue is #342

When using the compact mode and clicking on the fan speed, the drop down don't show all available fan speeds.

**Steps to reproduce**

1. Use a vacuum with more than three fan speed levels
2. Set compact_view in card options (`compact_view: true`)
3. Click on fan speed

**Expected behavior**
See all available fan speed levels as in the previous version.

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

### `v2.4.1`:
![grafik](https://user-images.githubusercontent.com/26537646/164313075-27a13982-4c34-4617-8123-aa49ff475168.png)

The last option is not showed correctly, see below.

###  `v2.3.3`: 
Works correclty
![grafik](https://user-images.githubusercontent.com/26537646/164312828-92abb6d7-3073-49cf-a3a1-c20d23968096.png)

**Versions:**

- Release:  `v2.4.1`
- Browser: Firefox, Safari, Chrome
- HomeAssistant version: 2022.4.6

**Comment by denysdovhan** [comment]
Sorry, misunderstood your report. Fixed.
