### ISSUE TITLE
Error with new update v2.5.1

### ISSUE THREAD

**Issue by Mick51** [denysdovhan/vacuum-card#366]
![Capture d’écran 2022-04-20 230342](https://user-images.githubusercontent.com/40418405/164322830-c76b3a2b-47ec-498a-868b-3a12e75f411b.jpg)

## System Health

version | core-2022.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3674
Installed Version | 1.24.5
Stage | running
Available Repositories | 1097
Downloaded Repositories | 45

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 111.1 GB
disk_used | 11.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.14.0), File editor (5.3.3), RPC Shutdown (2.2), Samba share (9.5.1), Home Assistant Google Drive Backup (0.106.2), Terminal & SSH (9.3.0), Glances (0.15.0), Check Home Assistant configuration (3.10.0), SQLite Web (3.3.0), ESPHome (2022.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 33
views | 9
mode | storage

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.5.6
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 5
added_devices | 2

</details>

**Comment by Microbeen** [comment]
I have a similar problem

**Comment by auanasgheps** [comment]
Me too

**Comment by edenhaus** [comment]
In the console the following error is printed:
```
Uncaught TypeError: Error resolving module specifier “lit-element”. Relative module specifiers must start with “./”, “../” or “/”.
```
The bug was introduced with version `v2.5.0`

Please don't comment with "Me too" or similar comments, use the thumbs up  :+1:  instead :)

**Comment by LeandroIssa** [comment]
I have a similar problem!!!

**Comment by MrAlucardDante** [comment]
In the mean time, you can go into hacs, and redownload 2.4.1 while waiting for a fix

**Comment by V4n1X** [comment]
2.5.1 and 2.5.0 are defective. 
2.4.1 works as normal as i can see

**Comment by BH9FXK** [comment]
me too

**Comment by denysdovhan** [comment]
Hey folks, thanks for reporting! I'm having the same problem on my mobile devices though everything works fine on the desktop.

Unfortunately, I can't locate the problem so far. If anyone can help, I would be grateful.

**Comment by denysdovhan** [comment]
I don't see any changes that might be related to this problem: https://github.com/denysdovhan/vacuum-card/compare/v2.4.1..v2.5.1

Still investigating…

**Comment by pittbull** [comment]
Having the same issue even when downgrading, removing and reinstalling.

**Comment by denysdovhan** [comment]
Possible fixes have been pushed: https://github.com/denysdovhan/vacuum-card/commit/0828c08c818d46ff66b1116bdbc389a35efbf90e

Please, check if this helps.

**Comment by pittbull** [comment]
Confirming card is back - colors in greyscale thought.

**Comment by denysdovhan** [comment]
@pittbull this is the part of the release. People have been asking about it a lot.

If you don't like the new styling, you can override it with CSS customizations: https://github.com/denysdovhan/vacuum-card#theming

**Comment by denysdovhan** [comment]
Closing this. Seems to be resolved.

**Comment by pittbull** [comment]
Aha - my bad :) Thanks for solving the issue.

**Comment by Stooovie** [comment]
2.6.2 does the same thing. 2.6.1 is fine.

**Comment by Mick51** [comment]
Idem
