### ISSUE TITLE
Background color is incorrect when using theme

### ISSUE THREAD

**Issue by vmartinv** [denysdovhan/vacuum-card#371]
Describe the bug

I'm using the theme ios-dark-mode-red-alternative, after #353 which fixed #337 the UI is considerably better however it still needs improvement, as shown below.

### Steps to reproduce

1. Install and activate theme `ios-dark-mode-red-alternative` (any ios theme is affected though, they are available [here](https://github.com/basnijholt/lovelace-ios-themes))
2. Add vacuum card
3. Notice the background and borders are different than the rest of the widgets.

### Expected behaviour
Vacuum card should have the same style as the rest of the widgets (check screenshot for reference)

### Screenshot
<img width="948" alt="Screenshot 2022-04-22 at 21 39 41" src="https://user-images.githubusercontent.com/5374768/164791364-52c3da4c-4769-4bcc-99fa-330a14f616b4.png">

### Versions

Release: v2.6.0
Browser: chrome
HomeAssistant version: 2022.03.03

**Comment by denysdovhan** [comment]
I'll try to take a look at that. Help is appreciated.

**Comment by sharonna511** [comment]
Remove in vacuum-card.js

--vc-background:var(
    --ha-card-background,
    var(--card-background-color, white)
  );

![image](https://user-images.githubusercontent.com/20332051/171331194-93fe6806-6eed-417d-861b-4094166ab9e1.png)

**Comment by ams3401** [comment]
![1](https://user-images.githubusercontent.com/70864968/183559494-c04287f0-eb09-477c-90b0-5702d8e9df20.JPG)

Still like this after removing that line in vacuum-card.js

**Comment by joddye2** [comment]
With card-mod integration can be solved.
![Képernyőfotó 2022-10-14 - 21 01 53](https://user-images.githubusercontent.com/77693599/195921915-9af4d8db-fb64-4daa-8f72-30933578ad6e.png)

Install card-mod and add to yaml:

```
style: |
  div.toolbar {background: unset;}
  div.preview {background: unset;}
```

**Comment by denysdovhan** [comment]
We are using `--ha-card-background`. You can override it with `--vc-background` variable.
