### ISSUE TITLE
Extract an attribute from an entity in the card

### ISSUE THREAD

**Issue by dbochicchio** [denysdovhan/vacuum-card#375]
**Describe the solution you'd like**
Combine both entity_id and attribute, so we could get (and transform) something from an entity where the primary attribute is not what we want, without creating a new sensor.

ie:
```
   - entity_id: sensor.deebot920_last_cleaning
     attribute: timestamp
     value_template: '{{ value | timestamp_custom("%Y/%m/%d %H:%M:%S") }}'
     subtitle: Last job
```

**Comment by denysdovhan** [comment]
Seems like a good feature. Should be easy to implement. I'll be grateful if anyone can help.
