### ISSUE TITLE
Translation doesn't work

### ISSUE THREAD

**Issue by xiaxianguyue** [denysdovhan/vacuum-card#392]
**Before submitting a bug**

I updated to the latest version available
I cleared the cache of my browser

**Describe the bug**

I need to display Chinese,but it's still in english

**Steps to reproduce**

1. Manual install ,Only put vacuum-card.js file into config/www folder.
2. edit yaml
3. `- type: custom:vacuum-card`
   ` entity: vacuum.viomi_v7_255d_robot_cleaner`
   ` image: default`
   ` language: cn`
4. browser F12 disable cache and F5 refresh the page
5. still in english

**Expected behavior**
show chinese in the card

**Versions:**

- Release: [2.6.3]
- Browser: [ chrome]
- HomeAssistant version: [ 2022.5.1]
![屏幕截图 2022-05-16 214721](https://user-images.githubusercontent.com/6123951/168607427-b6c1f4c1-e01a-4a21-9b3d-2d775264a447.png)

**Comment by denysdovhan** [comment]
Try the latest version. The issue might also be related to the browser you're using. Please, let know if the issue is resolved for you.
