### ISSUE TITLE
How to integrade 360 Vacuum ?

### ISSUE THREAD

**Issue by TaxosTheSneaky** [denysdovhan/vacuum-card#396]
You said inside your documentation that it works with am 360 Robot Vacuum Cleaner.

How did you make it work?

I cant figure out how to make it.

**Comment by denysdovhan** [comment]
I don't have this vacuum cleaner. The supported models are reported by users, so I can't really answer your question.

**Comment by Tazzios** [comment]
I think it is a mistake currently there is no support for 360 vacuum cleaners in HA so how the user can use the vacuum-card is a mystery to me.

some info  (complex workaround to only start and stop it with alexa and vote option):
https://community.home-assistant.io/t/360-s6-vacuum-robot/124990/18

Maybe remove it from the list or ask how the user did it?
