### ISSUE TITLE
Support for different vacuum images

### ISSUE THREAD

**Issue by Shurov** [denysdovhan/vacuum-card#4]
**Is your feature request related to a problem? Please describe.**
Now only a single vacuum model image is "hardcoded" into the card.

**Describe the solution you'd like**
It would be great to have images of several most popular models (possibly, at least confirmed supported ones) so that this image would be configurable.

**Describe alternatives you've considered**
Possible solutions are:
- bundle (most popular) model images into the repo and have a parameter that chooses one
- have default image as is and expose the parameter to provide own image file

**Additional context**
N/A

**Comment by denysdovhan** [comment]
Thanks for reaching out!

Actually, there's an option called `image`. You can use it to pass any image of the vacuum you want. Just find the right image.
