### ISSUE TITLE
No service data at vacuum card

### ISSUE THREAD

**Issue by FelixGraf404** [denysdovhan/vacuum-card#409]
Hey,

The vaccum card shows "no service data" at HA.

Here the pics:

![no_data1](https://user-images.githubusercontent.com/105812017/172043255-3bb9dad9-8c0a-45c1-b04e-76e8546bc4fd.PNG)
![no_data2](https://user-images.githubusercontent.com/105812017/172043267-9b48bb13-1b76-45ae-a9cf-c5b17cf4226b.PNG)

Did I an setup fail?

My element-card for the vacuum show all the data (Filter left,side brush left,..)

Thx a lot :)

**Comment by FelixGraf404** [comment]
![no_data3](https://user-images.githubusercontent.com/105812017/172043554-0fa66f43-7353-484c-9fdf-e1594acfacb2.PNG)

This was my first idea to solve the problem, but the seconds from the data shown as hours...

**Comment by FelixGraf404** [comment]
My solution that work:

An example for 1 stat...

stats:
  default:
    - entity_id: sensor.roborock_vacuum_s5_filter_left
      attribute: null
      value_template: '{{ (value | float(0) / 3600) | round(1) }}'
      unit: hours
      subtitle: Filter

Cheers :)

**Comment by natbrood** [comment]
Amazing! I was looking for that
