### ISSUE TITLE
Dreame F9 room cleaning start/stop don’t work

### ISSUE THREAD

**Issue by ozel0t** [denysdovhan/vacuum-card#411]
Hey,
I don’t know if I’m to stupid for that Bus how I get the service.xxx command to work ? I don’t find any about that in the Manual. 
How I can configure that if in click the kitchen   button that my robot will clean this room ?

**Comment by denysdovhan** [comment]
Here's an example of vacuum services for Xiaomi vacuums. It should be something similar for you vacuum: https://www.home-assistant.io/integrations/xiaomi_miio#platform-services
