### ISSUE TITLE
Local svg image path not working/rendering

### ISSUE THREAD

**Issue by Paytrix** [denysdovhan/vacuum-card#414]
**Before submitting a bug**

[ x] I updated to the latest version available
[ x] I cleared the cache of my browser

**Describe the bug**

Setting the image to a local image Path, which does not show up / render. (Image .svg file)

**Steps to reproduce**

1. insert an image path of a .svg file
2. Save card
3. Refresh Browser / Restart Homeassistant
4. Doesn't show any image

**Expected behavior**

Shows image of the .svg file

**Screenshots**
The left one is a vertical stack where the first card is the custom:vacuum-card with an image path of `local/Bilder/deebot950.svg`.
The right one is a image card with an image path of `local/Bilder/deebot950.svg`.
![image](https://user-images.githubusercontent.com/22264872/175307883-03919784-1ffa-4a82-a7e1-97ef0b91e02c.png)

**Versions:**

- Release: [2.6.3]
- Browser: [chrome]
- HomeAssistant version: [2022.6.7]

**Comment by denysdovhan** [comment]
Can't reproduce this issue. Works fine for me. Double check you path for an image.

**Comment by colino17** [comment]
@Paytrix In case you never figured this out. You need a slash before your path.

```
/local/Bilder/deebot950.svg
```
