### ISSUE TITLE
Ability to translate the noise mode

### ISSUE THREAD

**Issue by royto** [denysdovhan/vacuum-card#44]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to translate the "noise mode" values

**Describe the solution you'd like**
Add mode translation available

**Additional context**
![image](https://user-images.githubusercontent.com/6990995/81795681-ab0b1d80-950c-11ea-8210-4b8e029260e9.png)

**Comment by denysdovhan** [comment]
This might be done in the same way as status localization works.

**Comment by krystiancharubin** [comment]
#62
