### ISSUE TITLE
Image Animations not working

### ISSUE THREAD

**Issue by barrycraig** [denysdovhan/vacuum-card#45]
Tried on Chrome and Safari for Mac and Chrome for Android. Also tried with default image and custom image. No animation is visible on the entity image while the vacuum is cleaning as shown in the Readme.

**Comment by denysdovhan** [comment]
Any debug info?

What the version of the browser? The version of the card? Logs in the console?

**Comment by ITensEI** [comment]
I have the same "issue" with my Deebot Slim2. The reason I think is because the animation is based on the status. Mine shows "auto", "edge", "spot", "returning", "stop". If the animation is based only on status then it won't work for all modes.
