### ISSUE TITLE
Actions scripts - are these magically created?

### ISSUE THREAD

**Issue by nickdos** [denysdovhan/vacuum-card#46]
The readme mentions that the `actions` config requires a service value in the form of: `service: script.clean_living_room`.

What is not clear, is how someone is to create these script files. I presume that the user has to create these, so it would be nice to provide some hints/links to the user on how to create these files.

**Comment by cschriel** [comment]
The service_data in the actions object isn't required. By default it uses the "normal" method of starting the vacuum. Using this object, you can change what service gets triggered by using the action button.

**Comment by nickdos** [comment]
Thanks - I get that its option but **I want it!**

What I don't know, is **how do I setup my vacuum to do zone cleaning via the `script.clean_my_room` method**?

**Comment by royto** [comment]
I used this article as inspiration when I created my scripts: https://hackernoon.com/how-i-set-up-room-cleaning-automation-with-google-home-home-assistant-and-xiaomi-vacuum-cleaner-9149e0267e6d

**Comment by denysdovhan** [comment]
> There is nothing in the readme.md about how to do this.

It shouldn't be in readme. This is not part of this project, but rather the part of HA and its integrations.

**Comment by nickdos** [comment]
> > There is nothing in the readme.md about how to do this.
> 
> It shouldn't be in readme. This is not part of this project, but rather the part of HA and its integrations.

I'd argue, that if your plugin depends upon an integration being installed, then the README should link through to the documentation for that integration/s. 

I looked on https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/ and there is **no mention of `script` anywhere on that page**. I'm still unclear what needs to be in the scripts to trigger zone cleaning. Looking at the `vacuum.xiaomi_miio` page, I can see examples for automations... is the idea that I create scripts that are equivalent to the zone cleaning automations? 

Scripts are quite new to HA, so I don't think you can assume average users know how to set them up.

**Comment by denysdovhan** [comment]
Let's add a link to scripts docs in README
