### ISSUE TITLE
Stat's not updating

### ISSUE THREAD

**Issue by EvertJob** [denysdovhan/vacuum-card#461]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**
I'm using a helper to determine if the vacuum has to be ignored for a day. I'm using the following yaml code to use the switch and get the status:
```type: custom:vacuum-card
entity: vacuum.ingrid
image: default
show_name: true
compact_view: false
stats:
  default:
    - entity_id: input_boolean.negeer_roomba
      subtitle: Negeer Roomba?
shortcuts:
  - name: Clean living room
    service: input_boolean.toggle
    icon: mdi:robot-vacuum-alert
    service_data:
      entity_id: input_boolean.negeer_roomba
```

It's shows "off" as expected but when I toggle the switch nothing happens.After reloading the page it's shows "on".
**Steps to reproduce**

3. See error

**Expected behavior**
Status should be changed when using the switch.

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [2.6.3]
- Browser: [Safari]
- HomeAssistant version: [Home Assistant 2022.10.0b0]

**Comment by denysdovhan** [comment]
This can't be solved at the moment. Changes don't happen instantaneously, it takes some time for HA to perform a change and report a new state back to the card.
