### ISSUE TITLE
Displaying nestled attributes

### ISSUE THREAD

**Issue by TheDK** [denysdovhan/vacuum-card#479]
I am using this card to show info about my lawn mower robot, which has relevant information shown like this: 

```
battery_level: 100
battery_icon: mdi:battery-charging-100
accessories: null
battery: 
cycles:
  total: 341
  current: 0
  reset_at: null
  reset_time: null
temperature: 11.6
voltage: 19.52
percent: 100
charging: false

blades: 
total_on: 29559
reset_at: 0
reset_time: null
current_on: 29559

error: 
id: 0
description: no error

```
As you can see, if you want to show bladetime or battery cycles data needs to be read from battery --> cycles --> total

I've tried a couple of ways but always failed. I could read those attributes into a template sensor, just wanted to check before if it would be possible directly.

Thanks for your work and all the best to your country and people!

**Comment by denysdovhan** [comment]
You can do that, just specify `batter.cycles.total` as an attribute. It should work just fine.
