### ISSUE TITLE
Trying to remove for a reinstall

### ISSUE THREAD

**Issue by BartProvoost** [denysdovhan/vacuum-card#481]
I'm trying to remove the module to be able to reinstall it (outdated installation and I moved), I deleted some files but it still shows up in HACS, but with an error it couldn't be loaded.

Any suggestions where to look?

**Comment by denysdovhan** [comment]
HA caches UI cards pretty aggressively. You should reset your HA frontend cache.

On mobile app it's: Settings > Companion App > Debugging > Reset Frontend Cache

On web: open devtools, press and hold reload button and choose Reset Cache or some like that.

There's a chance you will need to do that multiple times before card disappears from cache.
