### ISSUE TITLE
Borders are not compatible with HA 2022.11.0 

### ISSUE THREAD

**Issue by martin131** [denysdovhan/vacuum-card#482]
**Before submitting a bug**
[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**
Borders are not compatible anymore

**Steps to reproduce**

1. Update to HA 2022.11.x
2. Check borders on vacuum card

**Screenshots**

![vacuum](https://user-images.githubusercontent.com/4062374/203306964-4335bf85-66cf-4159-b1bd-5a92e7c84ba1.png)

**Versions:**

- Release: 2.6.3
- Browser: Chrome
- HomeAssistant version: 2022.22.x

**Comment by denysdovhan** [comment]
Hey! I'm currently can't fix this issue, since my HA instance is down most of the time, due to blackouts caused by russian missile strikes on our infrastructure. This shouldn't be hard: probably add `overflow: hidden` somewhere on parent element

I'd be deeply grateful for the PR 🙏🏻

**Comment by IDmedia** [comment]
@denysdovhan Stay safe!

@martin131 
Install card-mod and use this. I'm using it and it works on the latest version
```
    style: |
      div.toolbar {background: unset;}
      div.preview {background: unset;}
 ```

**Comment by Arn0uDz** [comment]
> 

Can you give an example because I can't get it work.

```
type: custom:vacuum-card
entity: vacuum.valetudo_kitt
image: default
card_mod:
  style: |
    div.toolbar {background: unset;}
    div.preview {background: unset;}
```

**Comment by martin131** [comment]
This works for me
![image](https://user-images.githubusercontent.com/4062374/214298208-a3c0b5ab-d0ae-4f91-a28d-ef8db6ea3fa7.png)

**Comment by Arn0uDz** [comment]
> This works for me
> 
> ```
> entity: vacuum.valetudo_robot
> image: default
> style: |
>   div.toolbar {background: unset;}
>   div.preview {background: unset;}
> ```

Thanks! 

Just adding the last 3 lines did the trick.

**Comment by RCGV1** [comment]
The fix worked, I was able to change the card configuration.

**Comment by RCGV1** [comment]
<img width="985" alt="Screenshot 2023-02-02 at 7 48 21 PM" src="https://user-images.githubusercontent.com/119711889/216522670-fd98a9da-8ca2-46d8-81b7-13ce47740a58.png">


Going to leave this here because I was confused about how to change it.
