### ISSUE TITLE
[cosmetic] Text cropped on mobile

### ISSUE THREAD

**Issue by Stooovie** [denysdovhan/vacuum-card#49]
On mobile or other smaller screens, text at the top left is cropped
[https://i.imgur.com/0iHbgFT.png](url)

**Comment by denysdovhan** [comment]
This is especially true for translations. What would you consider appropriate?

**Comment by Stooovie** [comment]
I'd probably place it at the bottom center, under or instead of the name.

**Comment by denysdovhan** [comment]
I'll consider that, thanks!

**Comment by Stooovie** [comment]
Getting better I see :))  

https://i.imgur.com/OxAkDix.jpg

**Comment by krystiancharubin** [comment]
Should be resolved with 1.4.0 release
