### ISSUE TITLE
Option to display/change number of iterations

### ISSUE THREAD

**Issue by k-a-r-g** [denysdovhan/vacuum-card#493]
Some vaccuums / vacuum firmwares allow to clean an area repeatedly for X times.
It would be great to have the option to display the set repetition number (for example in form of an entity) among the status icons in the upper left corner of the card.
Even better would be the option to change that entity, for example in the form of a drop down menu, among the shortcuts.

**Comment by denysdovhan** [comment]
You're welcome to contribute that change :)

**Comment by k-a-r-g** [comment]
I am actually trying. While I am proficient in C/C++, I have never done anything in JS. So this might be a long road...
