### ISSUE TITLE
Card is hidden after start

### ISSUE THREAD

**Issue by bduijnhouwer** [denysdovhan/vacuum-card#495]
When my vacuum start, the card is gone.
What am I doing wrong to always display the card?

**Comment by m4skime** [comment]
Same issue here

Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Vacuum : ecovacs T9

i noticed that is only when we specify stats for a state. I've tested witch cleaning, paused, returning. For each case, when the vacuum comes into the specific state, the card disapears.

temporary workaround : use only "defaults" in stats, or rename each states( eg "cleaning" in "cleaning-old") in waiting time of bugfix

**Comment by bduijnhouwer** [comment]
> Same issue here
> 
> Home Assistant 2022.12.6 Supervisor 2022.11.2 Operating System 9.4 Vacuum : ecovacs T9
> 
> i noticed that is only when we specify stats for a state. I've tested witch cleaning, paused, returning. For each case, when the vacuum comes into the specific state, the card disapears.
> 
> temporary workaround : use only "defaults" in stats, or rename each states( eg "cleaning" in "cleaning-old") in waiting time of bugfix

Thanks to your reply I found that this piece in my card is giving me problems:

                _- entity_id: sensor.vacuum_main_brush_left
                  value_template: '{{ (value | float(0) / 3600) | round(1) }}'
                  subtitle: Main brush
                  unit: hours_
