### ISSUE TITLE
Mi Robot Vacuum Mop 2 Pro support

### ISSUE THREAD

**Issue by RayBan91** [denysdovhan/vacuum-card#503]
Hello,
I need to change my first version of Mi Robot Vacuum Mop Pro on [Mi Robot Vacuum Mop 2 Pro](https://www.mi.com/en/product/mi-robot-vacuum-mop-2-pro/). Can I expect support of this vacuum too?
Regards

**Comment by denysdovhan** [comment]
I don't add support for vacuums, since I own only one model and can test this card only on my personal vacuum.

People are usually reporting that their vacuums work with this card. You should try this card with your vacuum and report back if it works for you.
