### ISSUE TITLE
UONI V980 support

### ISSUE THREAD

**Issue by impy101** [denysdovhan/vacuum-card#505]
**Is your feature request related to a problem? Please describe.**
I have a Uoni V980+ robot vacuum and so far I have used Tuya to control it. Home assistant recognizes it and added it but I just can't get this vacuum card to work. It does not show any info like the battery, status, worked hours etc. The "start" and "locate" buttons do work just fine, but that's about it.

**Describe the solution you'd like**
I would like for everything to work; start, stop, go back home, status updates etc.

**Describe alternatives you've considered**
I have tried all sorts of things so far, but I just can't get this card to work properly. I understand that home assistant has only added 4 entities for my vacuum cleaner, so I probably won't be able to see all the data from it that I want, but I should at least be able to add start/stop/home buttons to the card for it.

The entities I got are:
vacuum.robotstofzuiger
select.robotstofzuiger_mode
sensor.robotstofzuiger_total_cleaning_area
sensor.robotstofzuiger_total_cleaning_time

**Comment by denysdovhan** [comment]
This configuration should work for you:

```yaml
type: 'custom:vacuum-card'
entity: vacuum.robotstofzuiger
```

If it's not, then you probably this card can't handle you vacuum properly.
