### ISSUE TITLE
Start/Resume Button in toolbar

### ISSUE THREAD

**Issue by MelleD** [denysdovhan/vacuum-card#520]
**Is your feature request related to a problem? Please describe.**
For my eufy G10 hybrid vacuum robot, a start/resume button is sufficient instead of start, stop, pause.
This function is already available in the modal dialog.
Could this function also be used for the toolbar?

**Describe the solution you'd like**
Would like to toggle the toolbar and just use start/resume Button without switching to pause/stop.

See here: https://community.home-assistant.io/t/eufy-robovac-g10-hybrid/547335

**Comment by denysdovhan** [comment]
You can override it with `actions` object: https://github.com/denysdovhan/vacuum-card#actions-object
