### ISSUE TITLE
НЕТ ФАШИЗМУ НА УКРАИНЕ!

### ISSUE THREAD

**Issue by xrenznaet** [denysdovhan/vacuum-card#521]
К гражданам Украины!

РОССИЯ УНИЧТОЖАЕТ ФАШИЗМ В ВАШЕЙ СТРАНЕ! ОЧНИТЕСЬ! ГОНИТЕ ПРОЧЬ ВАШЕГО ЗЕЛЕНСКОГО  И ЕГО  ПРИСПЕШНИКОВ! ОН ВОР И ЖИД! КРАДЕТ ВАШИ ДЕНЬГИ И ВАШИ ЖИЗНИ!

**Comment by DavertMik** [comment]
Всё хорошо, спасибо за беспокойство, весь фашизм на Украине уничтожен, возвращайтесь домой.

**Comment by xrenznaet** [comment]
ты сам-то веришь в то, что сейчас говоришь? ты вероятно живешь не на украине и не знаешь реального положения вещей. вас все, абсолютно все уже начинают ненавидеть. вы изгои не только в своей стране, но и в странах, которые, якобы, вам помогают. единственная страна, которая может вам помочь выбраться из это выгребной ямы - это Россия. раскрой глаза, взгляни на мир по другому. поищи информацию не из ваших источников. ну или хотя бы наберись смелости и приедь в тот же мариуполь. посмотри, сколько всего там сделала Россия. ты будешь приятно удивлен. уже многие из ваших поменяли свою точку зрения по вопросу о СВО. научись думать самостоятельно, анализировать ситуацию, и просто верить людям, настоящим людям, а не этим ублюдкам из штатов, мелкобритании, франции, польши и прибалтийских стран. они давно уже захлебнулись в своей ненависти и  зависти к русскому народу. пора просыпаться, дружище. пора!
