### ISSUE TITLE
Cleaning mode selection 

### ISSUE THREAD

**Issue by brenard** [denysdovhan/vacuum-card#523]
**Is your feature request related to a problem? Please describe.**
My robot (Viomi V7 with Valetudo) support different cleaning mode : _Vacuum, Vacuum & Mop and Mop_. I would love to have possibility to view in Home Assistant the current cleaning mode and select another mode.

**Describe the solution you'd like**
Add a cleaning mode selection component like for vacuum speed.

**Describe alternatives you've considered**
I'm using Valetudo and I suppose I could implement cleaning mode selection in another dashboard card and call Valetudo MQTT service with the right payload for changing mode. Currently, I have to connect to Valetudo web interface to change cleaning mode before starting cleaning (from Home Assistant or directly in Valetudo web interface).

**Comment by denysdovhan** [comment]
Thanks for reaching out! You're welcome to contribute that feature.
