### ISSUE TITLE
Korean translation is not displayed in some states, sources and actions.

### ISSUE THREAD

**Issue by limitless00net** [denysdovhan/vacuum-card#527]
**Before submitting a bug**

[*] I updated to the latest version available
[*] I cleared the cache of my browser

**Describe the bug**
Korean translation is not displayed in some states, sources and actions.

**Steps to reproduce**
When the vacuum is docked, the 'docked' state is not translated in the card.

**Expected behavior**
When the vacuum is docked, the 'docked' state should translate to '도킹됨'.
Please merge this PR #525 

**Screenshots**
![20230510_187_1](https://github.com/denysdovhan/vacuum-card/assets/64896798/df085c94-317a-4aa6-abf4-2fccbb3848b1)

**Versions:**
- Release: v2.6.3
- Browser: Chrome
- HomeAssistant version: core-2023.5.2

**Comment by JaredZA11** [comment]
I'm getting a similar issue with fan / vacuum speed. It's pulling through in Chinese instead of English

**Comment by denysdovhan** [comment]
This is probably due to specific state ('Docked' with capital D). You can find all Korean translations here: https://github.com/denysdovhan/vacuum-card/blob/master/src/translations/ko.json
