### ISSUE TITLE
value_template doesn't work

### ISSUE THREAD

**Issue by Hussamfhaily** [denysdovhan/vacuum-card#528]
**Before submitting a bug**

[ x] I updated to the latest version available
[ x] I cleared the cache of my browser

**Describe the bug**

the value_template works fine in default stats section but it doesn't work while in cleaning mode!

**Steps to reproduce**

3. See error

**Expected behavior**

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: [e.g. 0.2.0]
- Browser: [e.g. chrome, safari]
- HomeAssistant version: [e.g 0.109.4]

**Comment by denysdovhan** [comment]
You didn't provide enough info about your problem. Please reopen with logs, screenshots, etc or open a new issue.
