### ISSUE TITLE
Card broken in ha 110.b4

### ISSUE THREAD

**Issue by BradleyFord** [denysdovhan/vacuum-card#54]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

All the icons are broken in ha 110.b4, well actually the buttons stop work but the icons are visible this is due to some large icon changes in 110.

You can see how your was fixed in this order custom card.
https://github.com/artem-sedykh/mini-humidifier/commit/a540e6f69693dc4010a8001d917773045af4df95

**Versions:**

- Release: latest
- Browser: Chrome
- HomeAssistant version: 0.110.b4

**Comment by krystiancharubin** [comment]
#59

**Comment by denysdovhan** [comment]
Fixed by #59
