### ISSUE TITLE
Integration installed but not usabel

### ISSUE THREAD

**Issue by Phoenix-DH** [denysdovhan/vacuum-card#544]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**
The frontend integration is installed via HACS, but is not available in Lovelance UI anymore.
I get the following error:
Custom element doesn't exist: vacuum-card.

Also a reinstall will not fiox the issue, also not a restart.

**Expected behavior**
Integration visible.

**Screenshots**
<img width="1067" alt="Screenshot 2023-06-14 at 08 06 22" src="https://github.com/denysdovhan/vacuum-card/assets/44058592/10851408-f118-41fb-9235-94ec8de0cfee">
<img width="623" alt="Screenshot 2023-06-14 at 08 06 43" src="https://github.com/denysdovhan/vacuum-card/assets/44058592/0b26e88d-ea31-4efa-a58c-b388b3792d62">
<img width="1018" alt="Screenshot 2023-06-14 at 08 07 07" src="https://github.com/denysdovhan/vacuum-card/assets/44058592/5aeb54ca-2b31-49d0-bf51-49cfd35fef10">

**Versions:**

- Release: latest
- Browser: all
- HomeAssistant version: 2023.6.1

**Comment by Tamsy** [comment]
Same with Xiaomi Miio integration on HA 2023.6.1 here: The card is now gone from Lovelance UI.

**Comment by oopiicaa** [comment]
It works for me even with the latest version (2.7.1 in HA OS 2023.6.1) - but the latest version for the other project from the same developer, purifier-card, does not (the same issue as here).

**Comment by lirtm** [comment]
I confirm. On .6.2 the same.

**Comment by Phoenix-DH** [comment]
It is working again, ghanks!

**Comment by lirtm** [comment]
> It is working again, thanks!

I confirmed it too.

**Comment by denysdovhan** [comment]
This kind of problem is usually related to caching problems. Please, clean up your cache.

**Comment by Tamsy** [comment]
Unfortunately up to the latest version the card dissapears whenever the vacuum is cleaning but reappers as soon as the vacuum as docked.
