### ISSUE TITLE
Shortcuts dont launch

### ISSUE THREAD

**Issue by lviciedo** [denysdovhan/vacuum-card#559]
Shortcuts dont launch, instead I get 'failed to call service script/clea..." the script work fine when I call them under scripts. card config below, thank you!

type: custom:vacuum-card
entity: vacuum.bob
actions:
  start:
    service: dreame_vacuum.vacuum_clean_segment
    service_data:
      entity_id: vacuum.bob
      segments:
        - 9
        - 7
        - 11
        - 10
        - 4
        - 6
stats:
  default:
    - attribute: filter_left
      unit: hours
      subtitle: Filter
    - attribute: side_brush_left
      unit: hours
      subtitle: Side brush
    - attribute: main_brush_left
      unit: hours
      subtitle: Main brush
    - attribute: sensor_dirty_left
      unit: hours
      subtitle: Sensors
  cleaning:
    - entity_id: sensor.bob_main_brush_left
      value_template: '{{ (value | float(0) / 3600) | round(1) }}'
      subtitle: Main brush
      unit: hours
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time
shortcuts:
  - name: Clean Living Room
    service: script.clean_living_room
    icon: mdi:sofa
  - name: Clean Master bedroom
    service: script.clean_master
    icon: mdi:bed-empty
  - name: Clean Kitchen
    service: script.clean_kitchen
    icon: mdi:silverware-fork-knife
  - name: Clean Bathroom
    service: script.clean_bathroom
    icon: mdi:bathtub
  - name: Auto Empty
    service: script.auto_empty
    icon: mdi:trash-can

**Comment by lviciedo** [comment]
resolved

**Comment by quotschmacher** [comment]
@lviciedo how did you solve your problem?
And could you please post an example script on how to clean a single room via script?
