### ISSUE TITLE
No translation on card?

### ISSUE THREAD

**Issue by andriej** [denysdovhan/vacuum-card#56]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

On latest version there's still lack of translation on the card:
![image](https://user-images.githubusercontent.com/6303489/82419536-d945ab80-9a7e-11ea-970e-fabdf132b7a9.png)
"Charging" should be translated according to this version (polish language)

**Versions:**

- Release: v1.1.0
- Browser: Chrome
- HomeAssistant version: 0.109.6

**Comment by krystiancharubin** [comment]
This card depends on local storage selectedLanguage variable.
Try setting your language in settings to something else and back to polish to see if issue is resolved.

**Comment by krystiancharubin** [comment]
#61 added a fallback on browser language to help user who never updated their language setting in ha

**Comment by andriej** [comment]
That (Profile -> Language change to EN -> Reload -> Profile -> Language change to PL) didn't help.
All other UI was translated.

**Comment by andriej** [comment]
That (Profile -> Language change to EN -> Reload -> Profile -> Language change to PL) didn't help.
All other UI was translated.

**Comment by tibortiz** [comment]
@andriej The issue is present for all the changes. There is clearly a bug in the card because when i'm editing the card the translation is present in the preview but on the Dashboard it's always using English

**Comment by xoxys** [comment]
For me translation is also not working somehow 
![image](https://user-images.githubusercontent.com/3391958/97094823-cb610b80-1658-11eb-8f2d-450384266498.png)

**Comment by czarnydlk** [comment]
i have got that same problem. Change language and back didnt help.

**Comment by d3m3trius** [comment]
same problem

**Comment by nerdosity** [comment]
same for me, also moved from english to italian didn't helped

**Comment by denysdovhan** [comment]
Try hard reloading the page and emptying the cache after switching the language. This is most likely the cache problem.
