### ISSUE TITLE
Support image entities as well as cameras for map

### ISSUE THREAD

**Issue by gazpachoking** [denysdovhan/vacuum-card#571]
**Is your feature request related to a problem? Please describe.**
Deebot4HomeAssistant changed the live map from being a camera entity to an image one. Seems there is only support for camera entities in this card.

**Describe the solution you'd like**
Support image entities as well as camera for the map view.

**Describe alternatives you've considered**
I currently have a separate picture card alongside the vacuum card.

**Comment by RJ1002** [comment]
For a workaround, you can go into the code editor then you should see `map: ` and just replace your `camera.` entity with the `image.` entity.
example: 
![example](https://i.imgur.com/tKwcSLE.jpg)
