### ISSUE TITLE
Option to hide buttons

### ISSUE THREAD

**Issue by Twsts** [denysdovhan/vacuum-card#6]
Hi!
Awesome card!

Would be nice to have an option to hide and/or customize the bottom left buttons "Clean" and "Locate vacuum". 

Also an option to show the mapstream only when cleaning would be neat!

**Comment by denysdovhan** [comment]
Thanks for reaching out!

Let's think about it.

**Comment by denysdovhan** [comment]
Published as `0.5.0`!
