### ISSUE TITLE
Card elements not working correctly

### ISSUE THREAD

**Issue by t0mcat1337** [denysdovhan/vacuum-card#623]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

Multiple issues with this card (installed via HACS) in HA:
1. When configuring the card in the GUI, switches ("Show Name...") are without function:
![image](https://github.com/denysdovhan/vacuum-card/assets/3826246/04549168-d9a4-4ccc-a7d5-3a11b8ff96cf)
(The elements remain at the card, whereas switches are turned off)

2. Missing Action Buttons (Pause, Stop, Resume...) in the toolbar, even when adding them in YAML:
![image](https://github.com/denysdovhan/vacuum-card/assets/3826246/79e67e1a-3f06-4c7c-abcb-3b59cdcb42c7)

BTW: Shortcuts seem to work:
![image](https://github.com/denysdovhan/vacuum-card/assets/3826246/5f2847e8-b8da-4c28-bd51-1ad1f92d6d6d)

**Steps to reproduce**

1. Install vacum-card with HACS in HA
2. Use the card

**Expected behavior**
Card elements should work

**Versions:**

- Release: 2.7.6
- Browser: Chrome, Firefox
- HomeAssistant version: 2023.10.1

**Comment by ekalle-swe** [comment]
same issue here.

**Comment by inguy24** [comment]
I concur. The functionality of this card has died. I have the same issue with changes not being made as mentioned above but I also cannot get shortcuts to work. Even after clearing browser cache it does not work. I even simplified my yaml down to thr basics as outlines in the Readme but it will not function as intended. I am concerned that over a month had gone by with no reply from the author.

**Comment by vsnthdev** [comment]
Yup, looks like this project needs a fork.
