### ISSUE TITLE
Works well on Roborock S8 por ultra, but time changes units randomly 

### ISSUE THREAD

**Issue by rarieg** [denysdovhan/vacuum-card#627]
So far this card is running well on the Roborock s8 pro ultra

The only issue that is going on is that the values change from hours to seconds randomly when the robot is running 

bellow are the screenshots and code 

![image](https://github.com/denysdovhan/vacuum-card/assets/88505856/8803b509-2f49-4cee-a001-edcbcbe11535)

what it looks like when running 

![image](https://github.com/denysdovhan/vacuum-card/assets/88505856/bcddfe9a-bc5c-4dee-b495-939f5aaafb22)

Code:

type: custom:vacuum-card
entity_id: vacuum.roborock_s8_pro_ultra
stats:
  default:
    - entity_id: sensor.roborock_s8_pro_ultra_filter_time_left
      attribute: null
      value_template: '{{ (value | float(0) / 3600) | round(1) }}'
      unit: hours
      subtitle: Filter
    - entity_id: sensor.roborock_s8_pro_ultra_side_brush_time_left
      attribute: null
      value_template: '{{ (value | float(0) / 3600) | round(1) }}'
      unit: hours
      subtitle: Side brush
    - entity_id: sensor.roborock_s8_pro_ultra_main_brush_time_left
      attribute: null
      value_template: '{{ (value | float(0) / 3600) | round(1) }}'
      unit: hours
      subtitle: Main brush
    - entity_id: sensor.roborock_s8_pro_ultra_sensor_time_left
      attribute: null
      value_template: '{{ (value | float(0) / 3600) | round(1) }}'
      unit: hours
      subtitle: Sensors
  cleaning:
    - entity_id: sensor.roborock_s8_pro_ultra_cleaning_time
      attribute: null
      value_template: '{{ (value | float(0) / 360) | round(1) }}'
      units: minutes
      subtitle: Cleaning Time
    - entity_id: sensor.roborock_s8_pro_ultra_cleaning_progress
      units: percent
      subtitle: Percentage Clean
entity: vacuum.roborock_s8_pro_ultra

And if anyone can point me if/how i can add a moping status that would be great too
**Versions:**

Running version 2.7.6

**Comment by miklosbagi** [comment]
Howdy,

> running well on the Roborock s8

Can I ask how? 
It doesn't look like the Xiaomi Home app has support for S8, and it doesn't look like vacuum-card supports Roborock app. Wouldn't be the first time when my eyes block my vision tho :D

**Comment by rarieg** [comment]
> Howdy,
> 
> > running well on the Roborock s8
> 
> Can I ask how? It doesn't look like the Xiaomi Home app has support for S8, and it doesn't look like vacuum-card supports Roborock app. Wouldn't be the first time when my eyes block my vision tho :D

I did not use the Xiaomi home app, I used the roborock app and integration in HA.

**Comment by miklosbagi** [comment]
Oh interesting - that's what I would've expected, but for some reason I cant't see the devices from the roborock integration there.  
Def some issue on my end, thanks for the heads up!

**Comment by boredomwontgetus** [comment]
I see the same issue on a Roborock S7. Looks like templates are not always evaluated correctly. It is very easy to watch when the robot is changing state (cleaning -> docking, ...). Refreshing the website fixes the issue temporarily.

**Comment by HoreaM** [comment]
> I see the same issue on a Roborock S7. Looks like templates are not always evaluated correctly. It is very easy to watch when the robot is changing state (cleaning -> docking, ...). Refreshing the website fixes the issue temporarily.

I have noticed the same exact issue with my Roborock S6 as well.
