### ISSUE TITLE
Make the location icon optional

### ISSUE THREAD

**Issue by murmelbahn** [denysdovhan/vacuum-card#63]
Hi,

when you active the show_toolbar the card generates an icon for the "locate" command. It would be nice if this icon is optional.

**Comment by denysdovhan** [comment]
Thanks! I will consider that!

**Comment by bachulator** [comment]
Hi,

Please consider icon scalability as well. After recent upgrade of HA (110) the icons have changed the scale. Before all the icon have had perfect alignment and fitted in the card boarders. Now some icons are shown partly in browser and some missing on mobile screen.

**Comment by mesut3000** [comment]
Hi,
I have some missing icons too on the toolbar. Please bring scalabilty.
