### ISSUE TITLE
value template not used after values get updated

### ISSUE THREAD

**Issue by mindgam3s** [denysdovhan/vacuum-card#650]
Before submitting a bug

[X] I updated to the latest version available
[X] I cleared the cache of my browser

Describe the bug

while the vacuum is running it updated values like 'current cleaning area' which gets updated in the custom:vacuum-card
BUT
it does not use the value template after an update and displays the plain data coming from the entity.

Steps to reproduce

Start Robot
track custom:vacuum-card data
See value-template not being applied
Expected behavior
Updated values appear by using the value template

Real behavior
Updated values appear unchanged

Screenshots

![vacuum_card_display_error](https://github.com/denysdovhan/vacuum-card/assets/34487011/68b6ac82-13ed-4675-8049-002a0e11cf0b)

Versions:

Release: v2.7.6
Browser: chrome
HomeAssistant version: 2023.11.3

**Comment by mindgam3s** [comment]
@ChrisChapman

**Comment by ChrisChapman** [comment]
Can confirm this is still an issue in latest version

![image](https://github.com/denysdovhan/vacuum-card/assets/1804289/8e9cbe08-ccb2-4211-981e-d67f9dc9f0dc)

**Comment by globalenergys** [comment]
Bug still present in v2.10.0
