### ISSUE TITLE
Live map camera loads CPU

### ISSUE THREAD

**Issue by vaproloff** [denysdovhan/vacuum-card#66]
Hello everyone!

I have a problem with displaying live map using this integration.
Everything works, but Chrome tab (on my PC) with this lovelace card starts to load CPU to 60-80% when using map camera (from Valetudo via MQTT).
And it also loads RPi CPU to 10% (instead of 2-3% at normal working)

When I remove parameter `map: camera.rockrobo_map` - problem disappears.
I have `picture-entity` card with the same camera entity - no problems, only live map within this custom card.

Using Chrome dev tools I've discovered that this custom card makes new requests for camera image approximately every 5-10 milliseconds infinitely (about 150 requests per second, and it can be more often, depends on CPU performance I think). And this process loads CPU.

Any suggestions to fix it?

_Originally posted by @vaproloff in https://github.com/denysdovhan/vacuum-card/issues/33#issuecomment-633241162_

**Comment by dedors** [comment]
I discovered a "heavy" load on my network causing nonstopp 4-12MB/s. It also causes my GPU to spin up its fans. 

I found the roots to be the vacuum-card when using the camera. When removing it, it does continue for some time, but after restart browser/tab it's back to normal.

I did a test with picture glance card and it does not happen there (below 20KB/s).

**Comment by docBliny** [comment]
Just adding my "me too" to this thread. Looks like there's an infinite loop on loading the vacuum maps.

**Comment by denysdovhan** [comment]
Unfortunately, I can't help with this issue, since I don't have a rooted vacuum with Voletudo firmware. I'd be grateful if someone could take a look at this issue.

**Comment by docBliny** [comment]
@denysdovhan Could you try to trace how often https://github.com/denysdovhan/vacuum-card/blob/master/src/vacuum-card.js#L108 is called? The map update seems to be happening outside the following check for changes to state. I didn't have the time to debug and understand when/how the `updated` method gets called. The HASS documentation (https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card/) does state `Home Assistant will call setConfig(config) when the configuration changes (rare)` but `Home Assistant will set the hass property when the state of Home Assistant changes (frequent)`, so if the latter is triggering the method, that might be a possible cause.

Another option might actually be to have a configurable update frequency on the map (regardless of a bug fix) allowing the user to specify how often the map should be updated.

**Comment by denysdovhan** [comment]
> Could you try to trace how often … is called?

It's called every time a prop gets updated. In the case of static image, it updates approx on every state change of the vacuum. However, in the case of a live map, it might update a way faster.

@docBliny allowing a user to set the frequency of updates might be a good solution. We can use throttling for that.

**Comment by vaproloff** [comment]
> @denysdovhan Could you try to trace how often https://github.com/denysdovhan/vacuum-card/blob/master/src/vacuum-card.js#L108 is called?

I don't know how to trace function calling by time, but, as I wrote in issue opening, in Chrome "Network" tab I have infinite requests for jpeg image named "camera.rockrobo_map?token=..." every 5-20 milliseconds (about 100-150 requests per second). I think if I have more powerfull CPU, requests will be even more often.

I can do more tests. You just say, please, what to do and how.

Configurable map updating frequency will be solution, yes.
But it will be better to somehow bind updating of a map in widget to camera image updating.

**Comment by daemongloom** [comment]
It's called too often. 
`        this.map.attributes.entity_picture + `&t=${new Date().getTime()}`;`
That line effectively kills cache as it has new URL every millisecond. Probably, it would be enough to switch "t" parameter to seconds.

I was not able to check it as HASS always loads original version of js from HACS for me. Editing file via samba addon, editing via file editor, restarting browser, HASS from its interface, restarting VM with HASS - nothing worked for me. I'll be able to check it myself if you can point me where that js can be cached.

**Comment by aalbul** [comment]
Hello.
Any updates on this?
Now you don't need a rooted device to see the map: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor

**Comment by denysdovhan** [comment]
@aalbul Wow, cool! Let me take a look on that.

**Comment by krystiancharubin** [comment]
https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/ba073d307c9c2e5d591a7102ede16a185349422f/dist/xiaomi-vacuum-map-card.js#L661

we should try that

**Comment by vaproloff** [comment]
Problem is not solved, why did you close the issue?
I have the same behaviour as it had been before update.

**Comment by krystiancharubin** [comment]
The card should be refreshing every 5 seconds now by default.
Try clearing your cache if you are experiencing high refreshes like before.

**Comment by daemongloom** [comment]
For me it works fine now, updated to latest version with HACS. Request goes every 5 seconds if vacuum is active. And there are no new requests when vacuum is paused/docked.

**Comment by vaproloff** [comment]
I've done all that following your recomendations.
And voila: everything worked as it should.
Sorry for my mistake!
And thanks!

**Comment by krystiancharubin** [comment]
no problem, glad that its working now.
we should probably add more troubleshooting steps in the readme.
