### ISSUE TITLE
No blue "overlay"

### ISSUE THREAD

**Issue by InterceptorDK** [denysdovhan/vacuum-card#67]
Can we please have an option to when you usea custom background picture it go all the way to the border and DONT have that blue tinged overlay on the whole picture.
![image](https://user-images.githubusercontent.com/52815418/82765513-d8fb3680-9e17-11ea-96ff-a51898fc55e7.png)

Other than that its a sweet card

**Comment by denysdovhan** [comment]
I believe this card doesn't work well with a photo. The image should be a drawing of a vacuum, with transparent background, png or svg.

Sorry but we don't have plans to implement this anytime soon.
