### ISSUE TITLE
State is not centered

### ISSUE THREAD

**Issue by miguelvelezmj25** [denysdovhan/vacuum-card#670]
**Before submitting a bug**

[Yes ] I updated to the latest version available
[ Yes] I cleared the cache of my browser

**Describe the bug**

The state of the vacuum is not centered.

**Steps to reproduce**

Added new vacuum card to dashboard, with default settings.

**Expected behavior**
The status of the vacuum should be centered with the card.

**Screenshots**
<img width="510" alt="Screen Shot 2023-12-16 at 3 37 31 PM" src="https://github.com/denysdovhan/vacuum-card/assets/8826119/84944a02-11c9-4650-a76b-76f02f80cb2d">

**Versions:**

- Release: v2.8.0
- Browser: Chrome, Android companion app, iOS companion app
- HomeAssistant version: 2023.12.3

**Comment by Nanny1988** [comment]
Same to me.

![Screenshot_20231217_120614_Home Assistant](https://github.com/denysdovhan/vacuum-card/assets/150074110/ba3a6863-05e8-4074-bf34-381c74f12628)

**Comment by joeblackdandt** [comment]
![image](https://github.com/denysdovhan/vacuum-card/assets/28639055/2083f091-6745-4eec-a4b7-8c5123c304cf)

**Comment by miguelvelezmj25** [comment]
Using v2.10.0, and it is still not centered
![Screenshot 2024-06-18 at 9 54 51 AM](https://github.com/denysdovhan/vacuum-card/assets/8826119/e19ba7e6-034f-4f40-8763-a2a2dd266eda)
