### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/vacuum-card#69]
Vacuum have `error` state and `error` attribute with the message of the error. We should display that error.

**Comment by RuslanNovak** [comment]
Example:
`type: 'custom:vacuum-card'
entity: vacuum.xiaomi_vacuum_cleaner
image: default
stats:
  default:
    - attribute: filter_left
      unit: hours
      subtitle: Filter
    - attribute: side_brush_left
      unit: hours
      subtitle: Side brush
    - attribute: main_brush_left
      unit: hours
      subtitle: Main brush
    - attribute: sensor_dirty_left
      unit: hours
      subtitle: Sensors
  cleaning:
    - attribute: cleaned_area
      unit: m2
      subtitle: Cleaning area
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time
  error:
    - attribute: error`

The button "Dock" should be visible in the error state.
