### ISSUE TITLE
Action Buttons Not Showing

### ISSUE THREAD

**Issue by kmlucy** [denysdovhan/vacuum-card#698]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

The only action buttons that show on the card are the start and locate ones. The others don't show, regardless of whether I manually define them or not. I have a Roborock S7.

**Steps to reproduce**

1. Install vacuum card
2. Configure

**Expected behavior**
The action buttons appear

**Screenshots**
![image](https://github.com/denysdovhan/vacuum-card/assets/13952475/0e3b5aed-3d53-4eff-96e0-8112708d7bdd)

```- type: 'custom:vacuum-card'
  entity: vacuum.downstairs_vacuum
  actions:
    start:
      service: vacuum.start
      service_data:
        entity_id: vacuum.downstairs_vacuum
    pause:
      service: vacuum.pause
      service_data:
        entity_id: vacuum.downstairs_vacuum
    resume:
      service: vacuum.start_pause
      service_data:
        entity_id: vacuum.downstairs_vacuum
    stop:
      service: vacuum.stop
      service_data:
        entity_id: vacuum.downstairs_vacuum
    return_to_base:
      service: vacuum.return_to_base
      service_data:
        entity_id: vacuum.downstairs_vacuum
    locate:
      service: vacuum.locate
      service_data:
        entity_id: vacuum.downstairs_vacuum
```

**Versions:**

- Release: v2.8.0
- Browser: Chrome, Home Assistant Android App
- HomeAssistant version: 2024.2.3

**Comment by kmlucy** [comment]
Nevermind, I didn't realize they were context sensitive. It's all good.

**Comment by diazepam69** [comment]
I have the same issue. What do you mean "context sensitive"?

Thanks!

**Comment by kmlucy** [comment]
Different buttons appear depending on the vacuum state (running, docked, stopped, etc.).
