### ISSUE TITLE
Card no longer displays

### ISSUE THREAD

**Issue by Delfairen** [denysdovhan/vacuum-card#714]
**Before submitting a bug**

[X ] I updated to the latest version available
[X ] I cleared the cache of my browser

**Describe the bug**

After the update to 2024.3 the Vacuum cards no longer display

**Steps to reproduce**

1. Go to 'Dashboard which contained the vacuum card'
2. Nothing shows
3. Edit and no preview is displayed but the entity is still selectable

**Expected behavior**
Card displays

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: v2.8.0
- Browser: Edge and Chrome
- HomeAssistant version: 2024.3

**Comment by MSirabella413** [comment]
I'm running into the same issue. Has anybody found a solution?

**Comment by rrooggiieerr** [comment]
I'm facing the same and get these errors in my Chrome Developer Tools console
<img width="513" alt="Screenshot 2024-03-08 at 12 40 43" src="https://github.com/denysdovhan/vacuum-card/assets/18603534/f491b9b7-b9e1-41cb-9fb0-768fd8c7cbb3">

**Comment by Wanick95** [comment]
Hi, I'm running the same issue since Home assistant march update

**Comment by Delfairen** [comment]
It looks like this has been fixed in https://github.com/denysdovhan/vacuum-card/commit/a25f254a5345cccab5a10892ec73f6cf1859fca7 I am trying to figure out a way to update as HACS is not showing an update

**Comment by Delfairen** [comment]
It looks like there needs to be a new release produced to be able to download and start using this.

**Comment by ristomatti** [comment]
Meanwhile, you can install it by adding my fixed version as a custom repository in HACS. I temporarily uninstalled the original one before installing as I don't know well enough how HACS works or if it could create a conflict. Multiple people reported it to work #699.

When installing, it will show as version v2.9.0 which might or might not be the version @denysdovhan will make it to be.

![image](https://github.com/denysdovhan/vacuum-card/assets/9029939/7abfcd49-518a-4f07-b488-01e702cb0a90)
![image](https://github.com/denysdovhan/vacuum-card/assets/9029939/0cd4572d-7497-4089-8a35-299b83609f54)

**Comment by ristomatti** [comment]
@Delfairen Please close this as it's now fixed in v2.8.1 of vacuum card. :+1:
