### ISSUE TITLE
HA can't correctly load custom card after locating JS file

### ISSUE THREAD

**Issue by cpaucar3** [denysdovhan/vacuum-card#76]
**Before submitting a bug**

[X ] I updated to the latest version available
[X ] I cleared the cache of my browser

**Describe the bug**

When I add to Resources using the UI (not yaml), HA logs show:
```
2020-05-31 16:10:29 ERROR (MainThread) [frontend.js.latest.202005195] http://192.168.0.107:8123/config/lovelace/resources:0:0 Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../".
```
So I edit the .js file to have the "./" suffix. Then a new error occurs:
```
2020-05-31 16:12:30 ERROR (MainThread) [frontend.js.latest.202005195] http://192.168.0.107:8123/config/lovelace/resources:0:0 Uncaught TypeError: Failed to resolve module specifier "custom-card-helpers". Relative references must start with either "/", "./", or "../".
```
So I add "./" to that. Then no more HA log errors show up but them when I try to add a manual card with
```
type: 'custom:vacuum-card'
entity: vacuum.vacuum_cleaner
```
in the Card Configuration I get `Error: Custom element not found: vacuum-card` as well as
```
Custom element doesn't exist: vacuum-card.
type: 'custom:vacuum-card'
entity: vacuum.vacuum_cleaner
```
**Steps to reproduce**

See above.

**Expected behavior**
I should see the card preview.

**Screenshots**
Chrome screenshot after adding the "./" to the `lit-element` and `custom-card-helpers` path. `vacuum-card.js` is the only file in my `config/www` folder.
![image](https://user-images.githubusercontent.com/10660203/83362296-2ae31580-a35e-11ea-9836-8c676db41e2e.png)
Firefox screenshot:
![image](https://user-images.githubusercontent.com/10660203/83362463-7518c680-a35f-11ea-981d-062155aa1c57.png)

**Versions:**

- Release: latest commit on master
- Browser: Both Chrome and Firefox on Windows, with and without Private Mode.
- HomeAssistant version: 0.110.4

**Comment by denysdovhan** [comment]
That's because you're including an uncompiled source file from this repo. Please, never do that.

You should use HACS or a file attached to the [latest release](https://github.com/denysdovhan/vacuum-card/releases/latest).

**Comment by cpaucar3** [comment]
I replaced the file with the one from the latest version `$ md5sum vacuum-card.js 
1e900f37051d2a7befac7840a9b65cac  vacuum-card.js`

The `TypeError` issue is still present with `lit-element`, so I installed HACS instead and added the card through there. It seems to work with my [DEEBOT N79S](https://www.ecovacs.com/global/deebot-robotic-vacuum-cleaner/DEEBOT-N79S). It gets battery and state data. It can send the locate action. Though the start/stop action and the normal/high action don't work through the custom card, all actions work through the default Lovelace card. Which means I should be able to fix it by adding custom actions to the `custom:vacuum-card` right?

Thanks for pointing me in the right direction!

**Comment by krystiancharubin** [comment]
This card uses the standard vacuum commands that homeassistant provides (https://www.home-assistant.io/integrations/vacuum/) so its likely that your particular vacuum implementation has issues or defines custom commands

**Comment by cpaucar3** [comment]
Yes I have it configured under the [ecovacs vacuum](https://www.home-assistant.io/integrations/ecovacs) integration which uses the [sucks python library](https://github.com/wpietri/sucks). So then I should be able to use the [python script](https://www.home-assistant.io/integrations/python_script/) integration to make a service wrapper for the sucks API, and then add the service as a custom action for this card. Is that how it goes?
