### ISSUE TITLE
Valetudo gen1 support

### ISSUE THREAD

**Issue by pkishino** [denysdovhan/vacuum-card#8]
**Is your feature request related to a problem? Please describe.**
when using this card with valetudo gen1, the attributes do not correctly show the data

**Describe the solution you'd like**
valetudo attributes such as mainBrush, sensor etc are named slightly different then in this card

**Describe alternatives you've considered**
I have manually updated the file locally to support valetudo naming, would need to use some good switch to know which device and hence which attribute naming to use

**Additional context**
here is example of my valetudo attributes:
```json
{
    "mainBrush": "103.4",
    "sideBrush": "3.4",
    "filter": "103.6",
    "sensor": "28.7",
    "cleanTime": "196.2",
    "cleanArea": "11859.0",
    "cleanCount": 570,
    "last_run_stats": {
        "startTime": 1588800816000,
        "endTime": 1588801930000,
        "duration": 1114,
        "area": "15.0",
        "errorCode": 0,
        "errorDescription": "No error",
        "finishedFlag": true
    },
    "state": "docked",
    "valetudo_state": "CHARGING",
    "zoneStatus": ["bedroom"]
}
```

**Comment by denysdovhan** [comment]
Should be fixed by `v0.3.3`
