### ISSUE TITLE
HACS warning

### ISSUE THREAD

**Issue by Enzokot** [denysdovhan/vacuum-card#82]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

Please check screenshots

**Steps to reproduce**

1. Go to HACS in interface
2. See Warning message
3. Try to reinstall module -> warning in log

**Screenshots**
![image](https://user-images.githubusercontent.com/43236573/84064463-4f2c9b00-a9cb-11ea-825f-3cf5f00814ac.png)
![image](https://user-images.githubusercontent.com/43236573/84064476-53f14f00-a9cb-11ea-8d01-1e12a3eca19a.png)

**Versions:**

- Release: 1.4.2
- Browser: Chrome
- HomeAssistant version: 0.110.5
- HACS version: 1.1.0

**Comment by denysdovhan** [comment]
This error doesn't seem to come from my card. It's should be related to HACS. Please, make sure you run the latest version of HACS and if the error persists, report it to HACS repo.

**Comment by Enzokot** [comment]
Last version of HACS
Ok.

**Comment by Enzokot** [comment]
[https://github.com/hacs/integration/issues/1320](#1320) in HACS repo
