### ISSUE TITLE
Use custom entities as sensor objects

### ISSUE THREAD

**Issue by CarterBrehm** [denysdovhan/vacuum-card#86]
**Is your feature request related to a problem? Please describe.**
This card currently allows for custom stats to be displayed, such as the lifetime of certain parts of the robot. However, this only works for attributes of the vacuum itself, not separate stat entities.

**Describe the solution you'd like**
I'd like to be able to use any arbitrary entity I have in Hass already to be displayed on the card. I currently use a [template vacuum](https://www.home-assistant.io/integrations/vacuum.template/) with my Shark Ion Robot, which means I can't add these stats as attributes, but only as template sensors.

**Describe alternatives you've considered**
As far as I'm aware, there's no way to add attributes to a template vacuum, so there is no way to get them on this card. Right now, I just have a vertical stack with a set of conditional cards on the bottom that shows these stats, but it looks messy compared to the original card.

**Additional context**
[My card right now](https://user-images.githubusercontent.com/26262673/84605834-1a569300-ae66-11ea-8fa3-2c36dd16a5df.png)

**Comment by rossiluis22** [comment]
Hi!, me too!, i would love to add my cleaning counter value (entity) to this amazing card :) hope someone could help us :)

**Comment by ArthurMalet** [comment]
Would be really nice!

**Comment by denysdovhan** [comment]
Nice idea!

**Comment by denysdovhan** [comment]
Published as `v1.9.0`!

**Comment by ArthurMalet** [comment]
Awesome!
I couldn't manage to install it by bypassing HACS (with only propose 1.6, even when selecting "include beta version"). But I'm sure it's gonna be really nice with the next 1.9 release!
Thanks!
