### ISSUE TITLE
UI Helper formatting issue in 0.112b0

### ISSUE THREAD

**Issue by firstof9** [denysdovhan/vacuum-card#92]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

When attempting to edit the card in 0.112b0 the UI is mangled.

**Steps to reproduce**

1. Edit Card from UI

**Expected behavior**
Non-mangled UI

**Screenshots**
![image](https://user-images.githubusercontent.com/1105672/85808667-70e78b00-b70a-11ea-8274-8fc4f3d2eacf.png)

**Versions:**

- Release: 1.6.0
- Browser: Chrome
- HomeAssistant version: 0.112b0

**Comment by goncharov** [comment]
Confirm this in 0.112 release.
Seems behavior of `ha-switch` was changes in https://github.com/home-assistant/frontend/pull/6133 and now it is required to be wrapped by `ha-formfield`

![Screenshot 2020-07-02 at 09 31 06](https://user-images.githubusercontent.com/351309/86324193-dbd31d80-bc46-11ea-8f88-c528b1dc577e.png)

**Comment by krystiancharubin** [comment]
Is this still an issue? I'm running 0.115.6 and everything appears fine.

**Comment by firstof9** [comment]
No this does appear solved card version 1.11 HA version 0.116b4.
