### ISSUE TITLE
Be able to set 'number of cleanups' before running the vacuum

### ISSUE THREAD

**Issue by fi-sch** [denysdovhan/vacuum-card#94]
Hi!

**Is your feature request related to a problem? Please describe.**
I used another custom card for vacuum cleaner and I'm just lacking this functionality here :)

**Describe the solution you'd like**
I'd like to be able to simply set desired number of times that vacuum should clean specified area or do a complete cleaning. As I don't need 'play' and 'locate' buttons at all it could be simply another button like that – just a digit that would change "on-tap" from 1 to 3.

**Describe alternatives you've considered**
A dropdown in the 'preview' section. Probably it would be best to have it next to "mode" (e.g. Standard) setting.
BTW, it would be really nice to be able to set the cleanup mode from there also.

**Additional context**
This is the card that I was using recently: https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
Right now I use both of those cards (yours ant this one), both in one custom swipe-card.

Thanks!

**Comment by KTibow** [comment]
I'm pretty sure that's what the custom `actions` are for. You could make a script that does that, and have it call that.

**Comment by denysdovhan** [comment]
You're free to open a PR if you need that feature. I'll gladly review that PR.

Unfortunately, I don't have enough time to work on everything.

**Comment by fi-sch** [comment]
No problem, I totally get it. If only I know anything about coding in python, I would definitely add that feature :)

**Comment by denysdovhan** [comment]
@fi-sch FYI, this card is 100% in JS.

**Comment by fi-sch** [comment]
Thanks. Doesn't matter much to me as I'm no coder at all :/

**Comment by KTibow** [comment]
I'm fine to add that feature, can you give an example service call?

**Comment by fi-sch** [comment]
> I'm fine to add that feature, can you give an example service call?

It would be something like example below – 'repeats' parameter is available when using 'xiaomi_miio.vacuum_clean_zone' service. [source: https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-mi-robot-vacuum]

```
    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum
        repeats: '{{states('input_number.vacuum_passes')|int}}'
        zone: [[30914,26007,35514,28807], [20232,22496,26032,26496]]
```

**Comment by KTibow** [comment]
Hmm. Is there a way to tell it to clean all zones? Is zoning already built in?

**Comment by fi-sch** [comment]
Zoning seems to be built into the card and I would use repeat feature with zones. I don't use "clean all zones" at all.

I assume that if you would like to use 'repeat' parameter with "clean all" use-case, you would need to pass all the zones into the 'zone' parameter. I suppose that there's no 'repeat' for simple "clean (all)" command, because if you would tell your vacuum to clean a whole apartment multiple times, it would run out of battery before finishing the task.

**Comment by denysdovhan** [comment]
You can pass the number of repeats in the service data.
