### ISSUE TITLE
select map

### ISSUE THREAD

**Issue by rhgiter** [denysdovhan/vacuum-card#95]
option for select map.

multi floor is now available  for some robots (mine s5max roborock)   it auto detect the floor it is on (ex. map2), but when returning to the dock it dont choose the map where the dock is.(map1)  

1**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by krystiancharubin** [comment]
We only provide an option to render live map when you run Valetudo custom firmware on your vacuum. You would need to ask for map support there. My understanding is that it's currently not compatible with Gen3 roborock vacuums. That includes S5Max S4 S6
