### ISSUE TITLE
Information regarding stats attributes available and fan speed.

### ISSUE THREAD

**Issue by emsilva** [denysdovhan/vacuum-card#96]
Hello there, first of all, great job on this implementation.

I have two Roomba's, one i7 and one 980. Both are integrated in my HA already.
With the vacuum-card I can perform stop/start/home on both robots, see the square-meter covered and the cleaning time. I can't see any stats like hours on the filters, etc. I imagine this is because my stats are not available, would you please explain what I need to do in order to be able to see what are the stats I can use on these robots?

Also, my 980 shows me selection for fan speed. The I7 does not. Any reason that should be the case?

**Comment by krystiancharubin** [comment]
Regarding the status they are fully customizable for every state of the vacuum. As long as it's exposed as an attribute on the entity you can use it. There is an example in the readme. You can figure out which attributes are available from the dev tools area if HA.
